### ISSUE TITLE
Implementing a billing system

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#1]
The **billing system** must be able to:

- _Generate_ a full report of delivered meals per month: HTML + PDF
- _Generate_ an invoice per client, per month

TODO: À compléter

**Comment by maximest-pierre** [comment]
The best way to implement billing is by having a model billing. That way we can have a history of the billing summary inside of sous-chef.

**Comment by maximest-pierre** [comment]
<img width="433" alt="screen shot 2016-08-08 at 12 58 32 pm" src="https://cloud.githubusercontent.com/assets/7928135/17488540/dcb41750-5d67-11e6-81af-a6d8717783a5.png">
