### ISSUE TITLE
Migrate to Transifex for the translation system

### ISSUE THREAD

**Issue by cormier** [savoirfairelinux/sous-chef#119]
Transifex is free for open source projects and it has Github hooks. I believe that using Transifex could help us simplify the translation workflow and thus help translators that don't have a strong technical background contribute to the project.

 To use Transifex we would need to:

- [x] Create a Transifex organisation / project
- [ ] Configure the proper github hooks to synchronise the strings from git
- [ ] Update the instructions in the i18n section of the README to explain the Transifex workflow

**Comment by RignonNoel** [comment]
I think you talk about: https://www.transifex.com/customers/open-source/ ?

Have you some screenshot? Or documentation on the integration with github?

I just want see how it commit in github.

**Comment by manumilou** [comment]
http://docs.transifex.com/integrations/django/

**Comment by manumilou** [comment]
I created a project in Transifex: https://www.transifex.com/savoirfairelinux/sous-chef/
