### ISSUE TITLE
Plan the data migration

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#164]
### Expected Behaviour

The data contained in the old system should be migrated into the new system, including:
- Client information
- Orders history 

The old database is MySQL. 
### Actual Behaviour

No data have been migrated.
### Things to do
- What do we use ?
- How do we proceed ?

**Comment by lafe3402** [comment]
Hi,

I'm Eric Lafontaine and I would like to understand how you want to plan for the migration.

For that, we require to have the Data Structure that we want to export and make the mechanism to convert the Data into the new Data Structure.  

I believe we should hold on before we migrate the data until we have MVP so to develop this as a feature (for a client wanting to migrate) other than part of the actual product.

My thoughts, let me know what you think.

Regards,
Eric Lafontaine
