### ISSUE TITLE
Contribute missing translations

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#213]
### Expected Behaviour

* The po files should be up-to-date
* The application must be fully translated.
  
### Actual Behaviour

* The po files are not up-to-date
* A lot of strings are not translated at all.

**Comment by manumilou** [comment]
@maximest-pierre Can you please make sure the po files in the dev branch are up-to-date ? Thanks!

**Comment by guillaumep** [comment]
Je regarde celui-ci pour ce soir!

**Comment by manumilou** [comment]
Thanks @guillaumep and @madmath
