### ISSUE TITLE
[CM Step 2] Allow ingredient selection for the day

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#241]
### Expected Behaviour

This second step of the Client Management process must provide a way to add ingredients for the day.

- [ ] A Dish can be selected among a list of all created dishes (clean-up UI)
- [x] The menu selection fills the ingredients list
- [ ] The ingredient list can then be edited manually to add/remove ingredients (clean-up UI)
- [x] A next button must be available to go to the step 3.

### Actual Behaviour

Not implemented yet.

**Comment by manumilou** [comment]
![img_20160703_165536739](https://cloud.githubusercontent.com/assets/212768/16547535/a57112c8-413f-11e6-9ff2-b9c0bb4ea5b2.jpg)

**Comment by manumilou** [comment]
@lamontfr Any news on this?

**Comment by lamontfr** [comment]
@manumilou I've got it working (ingredients add/remove, search for subset of ingredients, save to db). I still have to clean up the code and the UI and to write tests. I hope to to a PR tonight.

**Comment by lamontfr** [comment]
The UI widget is not elegant. Must replace with Semantic UI widget (see PR https://github.com/savoirfairelinux/santropol-feast/pull/303)
