### ISSUE TITLE
Allowing multiple roles and users

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#3]
## Objectives

Each person that connects to Feast must be connected with his own user.

Roles are not defined yet.

**Comment by adasilva** [comment]
users also need an avatar or photo to display on their "card" which is currently displayed on the home page (santropol-feast/django/santropolFeast/page/templates/pages/card.html)

**Comment by lingxiaoyang** [comment]
@manumilou  Is this still valid?

We now have staff role in PR #570 and avatar in PR #595.

**Comment by erozqba** [comment]
I think this is not valid anymore, I'm closing it and we can reopen if needed.
