### ISSUE TITLE
The mobile menu does not open

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#327]
### Expected Behaviour

On resolution lower than 1200 px wide, the sidebar menu is replaced by a dropdown menu, that should open when clicking on the hamburger menu icon.

### Actual Behaviour

On resolution lower than 1200 px wide, the sidebar menu is hidden, but the dropdown menu does not open when clicking on the hamburger menu icon.

### Steps to reproduce

* Open the application
* Use CTRL+SHIFT+M to open the developer tool (on Firefox)
* Change the resolution for one lower than 1200 px
* See that the dropdown main menu does not open

**Comment by Tonours** [comment]
Hi,

A pull request has been made to fix this. 
See : https://github.com/savoirfairelinux/sous-chef/pull/341
