### ISSUE TITLE
In "Review Orders" Button "Refresh orders" creates a "latin" Component

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#336]
### Expected Behaviour

Refresh orders should just create orders and their items for the day.

### Actual Behaviour

Refresh orders uses a "Menu factory" before creating orders and their items for the day.

### Action to fix 

Remove call to "Menu factory" in delivery/views.py refreshOrders()

**Comment by manumilou** [comment]
I think this one is fixed by now. Reopen if it's not the case.
