### ISSUE TITLE
Make relationships easier to use in the admin

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#346]
### Expected Behaviour

In the admin, many to many relationships should be obvious, for example on the Clients page we should be able to read and update his(her) Restricted_items
### Actual Behaviour

Must open the Restrictions page and see each occurence as a separate row.

**Comment by manumilou** [comment]
@lamontfr It should be fixed by #343 as well, but it is good to have it in the django backend, if it is not too long to implement.
