### ISSUE TITLE
The createnotes management command tries to import import non-existing NoteFactory

### ISSUE THREAD

**Issue by cormier** [savoirfairelinux/sous-chef#355]
### Expected Behaviour

When running:
```
python manage.py createnotes
```
I expect the management command to create notes.

### Actual Behaviour

```
File "/code/django/santropolFeast/member/management/commands/createnotes.py", line 2, in <module>
    from member.factories import NoteFactory
ImportError: cannot import name 'NoteFactory'
```

There is no `NoteFactory` class in member.factories

### Steps to reproduce
```
python manage.py createnotes
```

**Comment by maximest-pierre** [comment]
The note factory has been change to the note application 

from note.factories import NoteFactory
