### ISSUE TITLE
Convert "through" models to ManyToManyFields

### ISSUE THREAD

**Issue by cormier** [savoirfairelinux/sous-chef#357]
Instead of using ManyToManyFields for 1..n relationships, "through" models are defined. This results in added complexity in writing code that queries the database.

Here is an example from the source:

Clients have ingredients that they wish to avoid. Those are defined by the model `Client_avoid_ingredients` in https://github.com/savoirfairelinux/sous-chef/blob/c3e1791876bd8058c82cadc05cf070604351b40d/django/santropolFeast/member/models.py#L749.

If one wants to have the list of the ingredients a particular client wants to avoid, the following code has to be used:

``` python
client_avoid_ingredients = Client_avoid_ingredients(client=client)
ingredients = [ingredient for client_avoid_ingredient.ingredient in client_avoid_ingredients]
```

With a ManyToManyField, it would be possible to have this list directly:

``` python
ingredients = client.ingredients_to_avoid.all()
```

If one wants to have the list of clients who wants to avoid a specific ingredient, the following code has to be used:

``` python
client_avoid_ingredients = Client_avoid_ingredients(ingredient=ingredient)
clients = [client for client_avoid_ingredient.client in client_avoid_ingredients]
```

With a ManyToManyField, this list would be more easily accessible:

``` python
clients = Client.objects.filter(ingredients_to_avoid=ingredient)
```

The code, in its current form, acknowledges the need for an easy way to get the list of ingredients in the context of a client. This is why the `ingredients_to_avoid` property has been introduced:

https://github.com/savoirfairelinux/sous-chef/blob/c3e1791876bd8058c82cadc05cf070604351b40d/django/santropolFeast/member/models.py#L466

However, defining `ingredients_to_avoid` as a M2M field would provide a much easier way to access it. Also, it would reduce the complexity of the code by removing the `Client_avoid_ingredient` model.

Furthermore, properly defining the relationships between the models could help us work towards implementing a pure Django solution to #339
## Todo

Here is the list of the models that serve no other purpose than implementing a 1..n relationship and that should be converted to Django m2m fields:
- [ ] Client_avoid_ingredient
- [ ] Client_avoid_component
- [ ] Client_option
- [ ] Restriction
- [ ] Component_ingredient
- [ ] Incompatibility
- [ ] Menu_component
- [ ] Order_item
- [ ] OrderBilling

**Comment by lamontfr** [comment]
@cormier @manumilou @erozqba The way it was designed originally was to have the M2M through model AND the many to many field. The latter was not yet there so some contributors added the property. For example  :  
```python
    ingredients_to_avoid = models.ManyToManyField(
        'meal.Ingredient',
        through='Client_avoid_ingredient'
    )
 ```
instead of : 
```python
    @property
    def ingredients_to_avoid(self):
        """
        Returns ingredients to avoid associated to this client
        """
        return Client_avoid_ingredient.objects.filter(
            client=self.id,
        )
 ```
This way the Client_avoid_ingredient model is just an explicit declaration of the underlying M2M table. These are used directly by the Kitchen Count queries. Also, some M2M models have other attribute fields, not just the foreign keys,

**Comment by lamontfr** [comment]
As discussed with @manumilou I will fix this issue as proposed in my comment above and I will remove the superfluous models (those having only foreign keys). Please hold PR #354.

**Comment by cormier** [comment]
Thanks @lamontfr . I believe most of the models listed above have only foreign keys. However, you are right, using these existing M2M models as "through" models is the best way to fix this issue.

I believe that a complete fix would require replacing the direct calls on the m2m models with calls on the parent model, but we can just replace those later as we go.

**Comment by cormier** [comment]
@lamontfr  I'd like to give a hand on resolving this issue. I will start by working on these models:

* Client_avoid_ingredient
* Client_avoid_component
* Client_option

I will use a 'through' m2m field as discussed. When I'm done, I will submit a PR, check the status of this issue to see where we're at and discuss on what to work next.

**Comment by cormier** [comment]
I have submitted a PR for Client_avoid_ingredient, Client_avoid_component, and Client_option. I will continue work on:

* Restriction
* Component_ingredient
* Incompatibility

**Comment by cormier** [comment]
`Component_ingredient` is a more complexe case. `Component` has a `get_day_ingredients` static method used in the kitchen count report.

**Comment by cormier** [comment]
I will start working on:

* Menu_component
* Order_item
* OrderBilling

**Comment by lamontfr** [comment]
This is no longer relevant.
