### ISSUE TITLE
Order Recap  page  fail when no LogEntry

### ISSUE THREAD

**Issue by rjacquemin** [savoirfairelinux/sous-chef#363]
It occurs when no order are created in system

![screenshot from 2016-08-21 15 42 11](https://cloud.githubusercontent.com/assets/12820060/17839447/350f2ba8-67b6-11e6-895f-eb29d154a7af.png)

Can be fixed by using the generateorders script 

### Steps to reproduce

* step 1
* step 2
* ...

**Comment by cormier** [comment]
I will look into this
