### ISSUE TITLE
The search icon is misplaced in the main menu

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#371]
### Expected Behaviour

In the right main menu, the search icon should be aligned with the labels attached to the other menu items.

### Actual Behaviour

The search icon is too much to the right.

![capture d ecran de 2016-08-25 00-51-18](https://cloud.githubusercontent.com/assets/212768/17957315/b0fced0e-6a5e-11e6-926b-f9420754614d.png)

### Steps to reproduce

* Open the application

**Comment by Microserf** [comment]
On it!

**Comment by Microserf** [comment]
Done and submitted as PR #408.
