### ISSUE TITLE
Move the Billing menu item to the proper section

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#372]
### Expected Behaviour

The Billing menu item belongs to the second part of the menu. It should be displayed under **Kitchen Count**. 

Beisdes, no labels should be attached to it.

### Actual Behaviour

A label is attached, and the menu item is not in the proper menu section.

![capture d ecran de 2016-08-25 00-51-18](https://cloud.githubusercontent.com/assets/212768/17957412/7b46fbf4-6a5f-11e6-8c04-6ee940a3c2ef.png)

### Steps to reproduce

* Open the application

**Comment by Microserf** [comment]
I will take a look at this

**Comment by Microserf** [comment]
Completed and submitted as PR #396.
