### ISSUE TITLE
The PDF option should be removed from the export button

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#374]
### Expected Behaviour

Only CSV export are supported. 

### Actual Behaviour

The dropdown proposes CSV and PDF.

![capture d ecran de 2016-08-25 01-04-35](https://cloud.githubusercontent.com/assets/212768/17957563/c6ee28b0-6a60-11e6-9b4b-31faced930ad.png)

### Steps to reproduce

* Click on the **Clients** or the **Orders** menu items. 
* For the clients list, you need to toggle the table view, instead of the Card view
* Click on the dropdown icon on the Export button

**Comment by ssirois** [comment]
I'll take a look at this real quick.
