### ISSUE TITLE
The client CSV export should use the status display name 

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#375]
### Expected Behaviour

The client's status should be displayed in full text in the CSV export.

### Actual Behaviour

The client's status is displayed as a code in the CSV export.

### Steps to reproduce

* Click on the **Clients** or the **Orders** menu items. 
* For the clients list, you need to toggle the table view, instead of the Card view
* Click on the dropdown icon on the Export button
* Open the CSV file and look at the status column. Only a letter is displayed.

**Comment by amedeedaboville** [comment]
I'd like to try this one.
