### ISSUE TITLE
The orders list should provide a pager

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#377]
### Expected Behaviour

The order list should displayed maximum 20/25 orders. Some kind of pager should be used to display more items.

### Actual Behaviour

All orders are displayed on the same page.

### Steps to reproduce

* Create batches of orders by running the script `python manage.py createorders`
* Click on the **Orders** menu item

Note: The createorders may crashes with an _Duplicate entry error_, as described by #356.
Some orders may be created anyway. Just re-run the script multiple times if necessary.

**Comment by Microserf** [comment]
I will look into this. :)

**Comment by Microserf** [comment]
Done and submitted as PR #406.
