### ISSUE TITLE
Gamification: allow users to select a profile picture

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#381]
### Expected Behaviour

A system user should be able to select a profile picture: could be an upload, or a choice among a selection. But should be fun and simple :-)
Gravatar maybe ?
### Actual Behaviour

A profile image is hardcoded.
### Steps to reproduce
- Open the application
- See the image profile on the right menu

**Comment by rjacquemin** [comment]
I will check this using 
http://django-avatar.readthedocs.io/en/latest/

it support gravatar
