### ISSUE TITLE
Security: Test that every route requires a login

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#382]
### Expected Behaviour

The application should only be available to logged-in users.
Clients informations, orders information, kitchen count process, billing should not be available if not logged-in.

Functional tests could be implemented at large to check this.

### Actual Behaviour

Most of the resources seem protected, but not sure ...

### Steps to reproduce

* Try some routes without being logged in

**Comment by ssirois** [comment]
I'll take a look at this and see if I can suggest a way to accomplish this automation.

**Comment by ssirois** [comment]
@manumilou Can you take a look at ssirois/santropol-feast@f6c56da0f61be2466127d0337297bad01e06c0f7 and tell me if you want to to do that on each "app"?

**Comment by ssirois** [comment]
@manumilou you can assign me this task. I should be able to work on this on the morrow or on the weekend.

**Comment by ssirois** [comment]
@manumilou unified login enforcement technique with rest of the code in ssirois/santropol-feast@1927bbc9b0ea3a527ac6d3eaf42876e557a90c1b

If it's OK with you, I'll continue like that with the other views.

**Comment by manumilou** [comment]
Yes, I like it, more elegant than subclassing LoginRequiredMixin
