### ISSUE TITLE
 Implement a flash message system (success, error and warning)

### ISSUE THREAD

**Issue by philippemouchel** [savoirfairelinux/sous-chef#383]
### Expected Behaviour

Need a flash message system to confirm/warn/alert us about actions in app.
Here is HTML code : http://semantic-ui.com/collections/message.html#warning
We should have **success**, **error** and **warning**.
Info isn't required.

For example. a message could confirm that you have correctly edit client infos, or alert you about an error in placing an order.

### Actual Behaviour

Nothing but a way to print message per client (but it,s not a flash message).

**Comment by manumilou** [comment]
Actions that should trigger a message:

* **Client view**: when the client status is changed, using the top-right dropdown
* **Client creation form**:  when the client is created, after the last step
