### ISSUE TITLE
Add a way to mark as read/unread multiple notes in one clic

### ISSUE THREAD

**Issue by philippemouchel** [savoirfairelinux/sous-chef#386]
### Expected Behaviour

On the notes list, we should have a checkbox per note, and a dropdown button to mark all checked notes as read/unread.
We should also have a way to select all read/unread notes using another dropdown buttons.
### Actual Behaviour

A button per note : we have to mark each note as read/unread.

**Comment by lingxiaoyang** [comment]
I'll take this.

I think page-wise "mark all as read" and "mark all as unread" buttons will be very helpful.

However, it doesn't make much sense to me to provide checkboxes - it needs to be clicked as well. But we can definitely improve the UI, to highlight the unread ones (even urgent ones). The grey buttons that we are using now are not visually meaningful:

![image](https://cloud.githubusercontent.com/assets/8630726/21946984/c8ef0bba-d9b0-11e6-92d9-4eae7a3e64d3.png)

Besides, I would use AJAX for changing read/unread status to prevent page refreshing. It's better to let the scrollbar stay there and commit the changes in the background.

**Comment by lingxiaoyang** [comment]
@manumilou Below are proposed changes. Let me know if you have other comments:

1. Emphasize unread notes
2. Change mark as read/unread buttons as "checkboxes".
3. Provide "Commit selected changes" and "Mark all as read".

![image](https://cloud.githubusercontent.com/assets/8630726/22000208/ea890e6c-dc0b-11e6-9961-6522e9eb5d0f.png)
