### ISSUE TITLE
Wrong link to client page on notes list

### ISSUE THREAD

**Issue by philippemouchel** [savoirfairelinux/sous-chef#387]
### Expected Behaviour

When we click on a client name in notes list, we should have client information page.

### Actual Behaviour

Currently, wrong URL, not available to load page.

### Steps to reproduce

* Go on notes list : http://0.0.0.0:8000/note/.
* If no notes, add one to a client (change his status will create one for instance) than back to notes list.
* Click on the client name and see.

**Comment by ssirois** [comment]
I'll take a look at this issue.
