### ISSUE TITLE
Provide a more interesting 404 page

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#391]
### Expected Behaviour

When trying to access a client view, or an order, that does not exists, it would be nice to display a more fun and custom 404 page. 

### Actual Behaviour

The default Django 404 page is displayed.

![capture d ecran de 2016-08-25 12-22-48](https://cloud.githubusercontent.com/assets/212768/17977271/06940c4c-6abf-11e6-8c8d-fbf649710ccd.png)

### Steps to reproduce

* Go to http://localhost:8000/member/view/1236/information

**Comment by ssirois** [comment]
I cannot help with design, but I can help with configuration.

I'll create a custom 404 handler in django.
