### ISSUE TITLE
Make Kitchen Count steps clickable

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#392]
### Expected Behaviour

The kitchen count steps should be clickable, to allow users to go directly to the step they want.

Semantic UI is used for the steps: http://semantic-ui.com/elements/step.html

### Actual Behaviour

You need to go through each step to land on the one you want.

![capture d ecran de 2016-08-25 14-10-34](https://cloud.githubusercontent.com/assets/212768/17980537/c3e284dc-6acd-11e6-9c2e-5ed9e4e9dcf6.png)

### Steps to reproduce

* Click on **Kitchen count** menu item
* Try to go the Kitchen count step directly

**Comment by marconius** [comment]
I can look into this!
