### ISSUE TITLE
I should be able to update every client information from the update form

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#393]
### Expected Behaviour

I should be able to update every information from the update form

### Actual Behaviour

Only basic information and address information is editable.

### Steps to reproduce

* Go to a client view
* Click Edit on the left column
* Try to edit other tabs than basic and address information
...

**Comment by amedeedaboville** [comment]
I repro'd this. I found 3 different issues:

1. On the Address tab, the save button doesn't work and in the browser console I get

`An invalid form control with name='route' is not focusable.`

2. In the referent information tab, clicking save gives a Django error with

`KeyError at /member/1/update/referent_information/
    'street'
`
3. The "payment", "preferences" and "emergency" tabs link to /update/basic_information.

I'll start with this last problem first, then look into the other two.

**Comment by amedeedaboville** [comment]
On that 3rd issue, it looks like there should be `payment_information.html`, `dietary_restriction.html`,  and `emergency_contact.html` pages in `/member/templates/client/update`.  It'll get to writing them.
