### ISSUE TITLE
Deleting an order from the order list resets the query params

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#411]
### Expected Behaviour

Query params should be kept after deletion.

### Actual Behaviour

Query params are reset.

### Steps to reproduce

* Go the order list
* Select a filter and click search
* Delete any order 
* The search filter has been reset

**Comment by Microserf** [comment]
If I may suggest an additional requirement, the `page=` parameter should be calculated to be the smaller of the two values: `page=` parameter on last request and current page count.

If you delete the last item when `page=5`, you would want that to be `page=4` on the next request, as `page=5` would raise an error.

**Comment by madmath** [comment]
#415 doesn't really address the comment by @Microserf, but addresses the original issue.
