### ISSUE TITLE
Provide proper translations for URL patterns

### ISSUE THREAD

**Issue by madmath** [savoirfairelinux/sous-chef#432]
### Expected Behaviour

URL patterns are translated to French e.g. /order/list becomes /commande/liste. 
### Actual Behaviour

Currently, French translations for URL patterns are the exact same values as their English counterparts. Also, it's possible not all patterns are translated in the project.
### Steps to reproduce
- Set your first accepted language to French (in Chrome, make sure French is the first item in chrome://settings/languages)
- See that the URLs are in French. 
### Notes

Translations can be changed, but the developer should also make sure that all url patterns are translatable via ugettext_lazy as explained [in the Django docs](https://docs.djangoproject.com/en/dev/topics/i18n/translation/#url-internationalization)

**Comment by lingxiaoyang** [comment]
Do we need to worry about non-ascii characters during the translation?

Related: https://docs.djangoproject.com/en/1.10/ref/unicode/#uri-and-iri-handling
