### ISSUE TITLE
Provides an option field attached to an order status change

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#444]
### Expected Behaviour

I should be able to select a reason when I change the status of an order to No Charge. The reason must be mandatory and should be selected among a list of reasons.

Possible reasons:
- Restrictions mistake
- Delivery mistake
- Really unhappy client
- .....
### Actual Behaviour

The status of an order can be changed without specifying any reason.

**Comment by lingxiaoyang** [comment]
I will reference how the client status is managed:

1. Upon any change of order status, there will be a "popup".
2. There will be an optional "reason" field, but the field is required when the new status is "No Charge".

In backend, I'll create a new model storing the reason information. The validation in (2) should also be implemented in the backend with proper unit tests.
