### ISSUE TITLE
Provide contact information for referant in New Client form (clsc case worker)

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/sous-chef#449]
### Expected Behaviour

We need to add 2 contact information entry boxes (1 for phone number and 1 for extension) for the referant in the New Client form.

### Actual Behaviour

Right now, there's only space for a name and the CLSC or Hospital making the reference.

### Steps to reproduce

none

**Comment by ssirois** [comment]
Looking at /member/create/basic_information/, the are already:

* *home phone* **and**
* *cellular* field

under "Contact information"

Would renaming *home phone* for *phone* and adding an optional *extension* to that field fix this issue or is it preferable to have a second phone field?

**Comment by philippemouchel** [comment]
Contact information are about referant, not about client.
So, I guess when I create a new client, when I have to create a new member to be his referent, I must fill his first/last name, plus a phone number, with extension (two different fields).

I'm on it!

**Comment by philippemouchel** [comment]
Actually, it's would be easier to provide only one field to fill referent contact. And if an extension is needed, just separate it with a _#_..
For instance : 514-276-5468#317

**Comment by erozqba** [comment]
@philippemouchel this is still a work in progress or is ready to be tested and merged?
