### ISSUE TITLE
Bug report when modifying a client referant

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/sous-chef#450]
### Expected Behaviour

updating a referant in a clients file
### Actual Behaviour

BUG
### Steps to reproduce
- click on CLIENTS on the home screen
- click on LOUISE DALLAIRE
- click on NO REFERANT AVAILABLE 
- update all the fields with generic info 
- click SAVE
  ![screenshot](https://cloud.githubusercontent.com/assets/21957643/18287501/6ec00ff2-7445-11e6-9339-143bf28c36a1.png)

**Comment by manumilou** [comment]
Updating a referent through the client form is not supported yet.
To edit a referent information, go to the client view and click the Referent link in the side menu.
Then click on the pen right to the section title. It should bring you to the Django backend.

If the referent does not exists yet, use this Django backend form: /admin/member/referencing/add/

**Comment by ssirois** [comment]
What would be the preferable path.

* The label shouldn't be a link if no reference **OR**
*  Implement the feature?

**Comment by manumilou** [comment]
@erozqba is working on the implementation: #393

**Comment by erozqba** [comment]
@manumilou manumilou closed this in #485 15 days ago
