### ISSUE TITLE
Be able to create multiple orders at once

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#477]
### Expected Behaviour

As a staff, i should be able to create multiple orders by selecting dates on a calendar.

### Actual Behaviour

Orders have to be created one by one.

**Comment by philippemouchel** [comment]
Fist of all, let's find a multiple date picker.
Found this one, and will try to use it in Sous-Chef app to verify compatibilty
https://github.com/dubrox/Multiple-Dates-Picker-for-jQuery-UI
