### ISSUE TITLE
Geolocalisation

### ISSUE THREAD

**Issue by pierline** [savoirfairelinux/sous-chef#481]
### Expected Behaviour

Locate the proper location on the map
### Actual Behaviour

Cannot find some of the addresses
### Steps to reproduce

Clients
New Clients
Personnal
Address

**Comment by manumilou** [comment]
@pierline Can you specify which addresses could not be geolocated ?

From what we've experienced, the address must be fully set for the geolocation to work. For instance:

7275 Saint-Urbain -> NO
7275 rue Saint-Urbain -> YES

The rue, boulevard, ... must be specify, otherwise the geolocation fails.

The East/West indications seems to be unreliabe at times as well.

**Comment by pierline** [comment]
The address set might have been the problem. Would be great if it could 
clearly outline the importance of spelling the addresses this way. 
Sometimes people don't know Mont-Royal is an Avenue and not a Street!

Pier

*Pier Liné*
/Directeur général
Executive Director/
514 284-9335
------------------------------------------------------------------------
<http://santropolroulant.org/fr/2016/09/invitation-officielle-gala-2016-le-jardin-enchante/> 
	*Avez-vous vos billets pour le Gala? *
Joignez-vous à nous le 27 octobre! 
<http://santropolroulant.org/fr/2016/09/invitation-officielle-gala-2016-le-jardin-enchante/> 


*Do you have your Gala tickets? *
Join us on October 27th! 
<http://santropolroulant.org/en/2016/09/official-invitation-to-enchanted-garden-gala/>

**Comment by rjacquemin** [comment]
FYI 
similar issue reported : 
http://stackoverflow.com/questions/11404735/geocoding-issues-with-openstreetmap-nominatim

**Comment by manumilou** [comment]
The current geocoder works as expected. It needs the complete address to be able to geolocate properly. We'll add a new issue if we switch the geocoding engine.
