### ISSUE TITLE
Prefered language

### ISSUE THREAD

**Issue by pierline** [savoirfairelinux/sous-chef#482]
### Expected Behaviour

Gives more than two option. For us it's important to know if clients speak English and French, if they are allophone, if they prefer an other language than English and French
### Actual Behaviour

Only two options: French - English
### Steps to reproduce

Clients
New Client
Personal

**Comment by manumilou** [comment]
Is it enough to have the following choices:

* French
* English
* Allophone

Or do you need to know which language the person speaks (in case of allophone I mean) ?

**Comment by pierline** [comment]
Two things here: idealy we would be able to have multiple choices + a 
data entry field where we could add a language!

*Pier Liné*
/Directeur général
Executive Director/
514 284-9335
------------------------------------------------------------------------
<http://santropolroulant.org/fr/2016/09/invitation-officielle-gala-2016-le-jardin-enchante/> 
	*Avez-vous vos billets pour le Gala? *
Joignez-vous à nous le 27 octobre! 
<http://santropolroulant.org/fr/2016/09/invitation-officielle-gala-2016-le-jardin-enchante/> 


*Do you have your Gala tickets? *
Join us on October 27th! 
<http://santropolroulant.org/en/2016/09/official-invitation-to-enchanted-garden-gala/>
