### ISSUE TITLE
Emergency contact

### ISSUE THREAD

**Issue by pierline** [savoirfairelinux/sous-chef#483]
### Expected Behaviour

More than one contact info = email + phone# at work + cellphone#... 
### Actual Behaviour

We can only pick one option (email OR phone# at work OR cellphone#)
### Steps to reproduce

Client
New client
Emergency

**Comment by manumilou** [comment]
![capture d ecran de 2016-12-08 16-47-33](https://cloud.githubusercontent.com/assets/212768/21029094/221d9d1c-bd66-11e6-8026-0b9a15e8dd21.png)

**Comment by lingxiaoyang** [comment]
@manumilou  Are all of them required, email/phone/cell? Or it's only necessary to have at least one?

**Comment by lingxiaoyang** [comment]
@manumilou Do we still need to write emergency contact information if we select an existing member as emergency contact?

![image](https://cloud.githubusercontent.com/assets/8630726/21032279/88803866-bd76-11e6-8869-d3cb2184e861.png)

**Comment by lingxiaoyang** [comment]
@manumilou   By the way, it seems that, in personal information, contact information is not required. This will pass the validation:

![image](https://cloud.githubusercontent.com/assets/8630726/21032329/d9a9cda6-bd76-11e6-84c9-25b548868b52.png)
