### ISSUE TITLE
Gender for new client

### ISSUE THREAD

**Issue by katrinaheyde** [savoirfairelinux/sous-chef#486]
### Expected Behaviour

Fill me in ...Would like to see a third option: "other" for clients who don't identify as male or female

### Actual Behaviour

Fill me in ...Only two options 

### Steps to reproduce

* step 1 new client 
* step 2 gender
* ...

**Comment by manumilou** [comment]
OK @katrinaheyde , we'll then have three options: Male, Female, Other

But question: isn't the following better:
Man, Woman, Other
