### ISSUE TITLE
Format phone number display

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#491]
### Expected Behaviour

The phone numbers should all displayed in the same manner. 
The proposed format here is: XXX-XXX-XXXX.
### Actual Behaviour

No standard format is used. The phone number is displayed as entered.
For the migrated data, phone numbers are imported in the database without any whitespace: XXXXXXXXXX.
### Steps to reproduce
- Import the fixtures
- Go on the client view
- Edit the client phone number by adding whitespace (for instance)
- See how it is displayed on the client view

**Comment by fpeyre** [comment]
I will make it with issue #330 (They have a form field for phone number who displayed it in the good format)

**Comment by manumilou** [comment]
@fpeyre This issue is also related to the display. Besides the field validation, phone numbers must be displayed in a consistent way. For instance, if phone numbers are imported through a script with no spaces, they should be displayed properly as well. Maybe a template tag?
