### ISSUE TITLE
No hardcoded URLs should be used in Javascript code

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#494]
### Expected Behaviour

Every URL in the application should use Django routing system. No URL should be hardcoded, either in django templates or Javascript.
### Actual Behaviour

Some URLs are hardcoded in the Javascript code here. See this comment for reference: https://github.com/savoirfairelinux/sous-chef/pull/478#discussion_r85555738

**Comment by philippemouchel** [comment]
I'll fix it myself, using HTML data attribtues or something like that.
Thanks @erozqba for the idea.
