### ISSUE TITLE
Kitchen Count Report needs a layout specifically for printing

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#498]
### Expected Behaviour

- Clear and properly sized character fonts
- Highlighting when required
- Maximize use of space on sheet
- Logo and header at top of each page

### Actual Behaviour

- UI is good for web page, but when printing the fonts become tiny and the column widths are not optimal.

### Proposed solution

- Generate a custom PDF in the view, as we do for labels.

**Comment by ssirois** [comment]
If I may, this could be done with a specific style-sheet addressing printers media.

Bonus would be that said style-sheet would benefit all views.

Generating a PDF for one particular view doesn't give a nice print layout to other views and a lot of work is needed for each view.

/ping @manumilou
