### ISSUE TITLE
Error message that is at the wrong place

### ISSUE THREAD

**Issue by red1laref** [savoirfairelinux/sous-chef#508]
### Expected Behaviour
The error message should be over the field it represent

### Actual Behaviour

The error message is in the top left of the screen
![bug_affichage_sous-chef](https://cloud.githubusercontent.com/assets/22602929/20201730/2ab04f18-a788-11e6-869e-7eeb71d13ca0.png)

### Steps to reproduce

* create a new client
* leave the route field empty
* click next

**Comment by lingxiaoyang** [comment]
The error message that you've seen is an HTML5 form validation message, as we have `required` attribute on the "route" select box. However, as we add `ui search dropdown` classes on the `<select>` box, we trigger Semantic UI performing a DOM replacement to [make it pretty](http://semantic-ui.com/modules/dropdown.html) but actually hiding the `<select>` element (if we inspect it we would find `display:none` on it). 

The result that you've shown is in fact browser-specific. In Firefox, the error shows at the top-left corner (as in your screenshot), and it could be repositioned by removing `display:none` but adding `visibility:hidden;position:absolute;top:0;left:0` on the `<select>` element. But in Chrome this fix doesn't work and there's even no error messages as long as the element is not displayed, whether with `display:none` or `visibility:hidden`! 

So maybe for sous-chef, we simply ask browser [not to perform the HTML5 validation](https://www.w3.org/TR/html5/forms.html#attr-fs-novalidate) by adding `novalidate` on the parent `<form>` element and still we'll have Django doing it for us (also with much prettier display). I think we should report this problem to Semantic UI, but let's not do the browser-specific hack ourselves. Anyone agrees?

**Comment by lingxiaoyang** [comment]
I looked more into this issue today. My conclusion would be: Semantic UI does not support HTML5 form validation ([link to a declined issue](https://github.com/Semantic-Org/Semantic-UI/issues/2373)), but it has its own front-end form validation functionalities. See [link](http://semantic-ui.com/behaviors/form.html).

So to resolve this issue, it seems that we'll have to disable HTML5 validation and it should be very easy. But perhaps we can list as an enhancement to add Semantic UI's validation settings in our front-end JS. How do you think? @manumilou
