### ISSUE TITLE
Emergency contact edit

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/sous-chef#517]
### Expected Behaviour

Should open an editing form

### Actual Behaviour

crash

### Steps to reproduce

* step 1= Click on any client to open their file
* step 2= Click on EDIT down in the Emergency contact field
* ...

**Comment by manumilou** [comment]
@JeanFrancoisFournier Is it consistent with every client?

**Comment by JeanFrancoisFournier** [comment]
bon matin! Yes every client.

**Comment by manumilou** [comment]
A patch has been deployed on your sous-chef instance. Can you confirm that it is working?
