### ISSUE TITLE
Create and display a billing summary for a given period

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#524]
### Expected Behaviour

* Be able to group the delivered orders per client
* A billing history must be attached per client 

### Actual Behaviour

* A billing lists only all billable orders for a given period. It is not grouped by client.

### Steps to reproduce

* Go to the billing page
* Click the + icon on top-right
* Create a billing for a period (make sure you have delivered orders in the database)
* Click on the billing newly created
* ...

**Comment by erozqba** [comment]
@manumilou , I will like to work in this but I have some questions for you:
1. If you can have differents client's orders grouped in the same bill, how you propose to attach a billing per client? 
2. Will the clients share the same bill ?
3. It will not be better create bills by date range (yeat-month) and client, so one bill will group only orders from a single client ?

I don't know how the real business work, so we should check with then to implement it the way it's more usable to them.

**Comment by manumilou** [comment]
@erozqba I am meeting with Santropol tomorrow to clarify the business rules relating to the billing. I'll let you know. It would probably be interesting to attach a client to a billing though.

**Comment by manumilou** [comment]
@erozqba We only need to able to output a list of clients, for a given billing period, containing the following information:
- Client's name
- Total Orders count
- Total main dishes count, with number of regular and large  
- Total amount
- Orders list (optional)

This would be displayed on the billing view page.
So no need in a first iteration to attach a billing to a specific client, neither displaying a billing history in the client's view.

**Comment by manumilou** [comment]
@erozqba Have you started working on this ?

**Comment by erozqba** [comment]
@manumilou Sorry, I don't have founded the time to do it... and I don't think I could do anything until the weekend. :(

**Comment by manumilou** [comment]
@erozqba No problem!

**Comment by lingxiaoyang** [comment]
I'll be taking the first iteration.

**Comment by lingxiaoyang** [comment]
@manumilou  Any suggestions on UI? 

![image](https://cloud.githubusercontent.com/assets/8630726/20987225/cf0d6a52-bc99-11e6-978a-e37963708a03.png)

Click on "view orders" --->
![image](https://cloud.githubusercontent.com/assets/8630726/20987233/d6982dc0-bc99-11e6-8ab4-7d686eaceaa7.png)
