### ISSUE TITLE
No login check on certain pages

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#527]
### Expected Behaviour

Related page: `http://localhost:8000/member/create`

I should be redirected to login page if I try to access this page while I'm not logged in.

### Actual Behaviour

However, it shows the form. It even redirects to the "address information" page as I just filled in the "personal information" page with administrator account. I can go back to the previous page although no information will be shown. At top-left corner the user name is shown as `()` (blank). I can see the number badge of clients/orders/staff notes in the menu at the left side.

### Steps to reproduce

* step 1: create a private window in the browser
* step 2: access `http://localhost:8000/member/create`

**Comment by lingxiaoyang** [comment]
This issue is also seen at:

`http://localhost:8000/delivery/order/`
`http://localhost:8000/delivery/meal/`
`http://localhost:8000/delivery/kitchen_count/`
`http://localhost:8000/delivery/routes/`

**Comment by lingxiaoyang** [comment]
Will also unit-test all routes.

**Comment by manumilou** [comment]
@ssirois did already a couple of unit tests.
