### ISSUE TITLE
Add "Sides" selection to Kitchen Count / Pick Ingredients

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#529]
### Requirements  (from meeting with JFF and JV on 2016-11-30)

- The main dish has its own ingredients which do not include the "Sides" which are two vegetables placed in separate sections of the meal container.
- SousChef must detect ingredient clashes in the Main Dish and list them on the Kitchen Count Report.
- SousChef must also detect ingredient clashes in the Sides and list them on the Labels. (see Issue #531)

### Expected Behaviour

- In the Pick Ingredients page, we should have one new multiple selection dropdown, for "Side Ingredients".
- The dropdown should allow filtering, ideally showing the ingredients whose name contains a string of characters. The latter be handled by Issue #532.

### Actual Behaviour

- All ingredients pertain to the Main dish.

**Comment by manumilou** [comment]
@lamontfr From what I understood, only one Side field should be enough. Both sides would be set in it then. What do you think?

**Comment by lamontfr** [comment]
@manumilou I agree with you, I also thought about it last night and this is a better approach. I edited the Issue.

**Comment by lamontfr** [comment]
@manumilou I made the changes, must now adjust test data.

**Comment by lamontfr** [comment]
@manumilou The changes are finished. I have to merge code from the latest commits of PR #528.
