### ISSUE TITLE
Revise Meal Labels Contents

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#531]
### Requirements (from meeting with JFF and JV on 2016-11-30)

- All labels should show : Client name, Delivery Date, Route
- If there is no ingredient clash with the main dish, show : the main dish menu name ; otherwise show : "Special _____________________" and the ingredients that clash (this will be the same combination of clashing ingredients that was shown on the Kitchen Count Report). 
- If there is an ingredient clash with the Sides, show : the client's restrictions that clash.
- If there is a meal preparation requirement : show it.
- If the meal serving is "LARGE" : show it.
- If the client has restrictions other than the clashes above : show the client's other restrictions.
- If the main dish menu name is shown according to the rules above and if there is enough room on the label, list the main dish ingredients.

### Revision 1 of requirements (from meeting with JFF and JV on 2016-12-07)

- The first line will show the Client name, the Route (centered on the line) and the Delivery date. If the route name is too long, an abridged name  will be have been added to the Database.
- The second line will show the main dish name (or '_________' if there are Main Dish clashes) and if the serving size is LARGE, this will be printed at the right end of the second line.
- The third line will start with 'SPECIAL' and will show the Dish clashes (this will be the same combination of clashing ingredients that was shown on the Kitchen Count Report - in Normal font) and the Preparations (in Bold font); if too long to fit, the text will wrap. If no Dish clashes and no Preparation, the line will be skipped and not left blank.
- The fourth line will show the Sides clashes (as specified by the client); if too long to fit, the text will wrap. If empty, the line will be skipped and not left blank.
- The fifth line will show the Other restrictions (as specified by the client); if too long to fit, the text will wrap. If empty, the line will be skipped and not left blank. "The other restrictions" = "the ingredients to avoid" + "the restricted items" - "the sides clashes".
- The main dish Ingredients will be printed only if there are no Dish clashes AND no Sides clashes.
- Il the client ordered many servings, there will be a separate label for each serving.

### Revision 1a of requirements (minor changes after PR #568, to be confirmed at next meeting with JFF and JV)

- The first line will show the Client name, the Route (centered on the line) and the Delivery date. If the route name is too long, an abridged name  will be have been added to the Database.
- The second line will show the main dish name (or '_________' if there are Main Dish clashes) and if the serving size is LARGE, this will be printed at the right end of the second line.
- The third line will start with 'Special' and will show the Dish clashes (this will be the same combination of clashing ingredients that was shown on the Kitchen Count Report - in Normal font).  If no Dish clashes, the line will be skipped and not left blank.
- The fourth line will show the Preparations (in Bold font); if too long to fit, the text will wrap. If no Preparation, the line will be skipped and not left blank.
- The fifth line will show the Sides clashes (as specified by the client); if too long to fit, the text will wrap. If empty, the line will be skipped and not left blank.
- The sixth line will show the Other restrictions (as specified by the client); if too long to fit, the text will wrap. If empty, the line will be skipped and not left blank. If there are Sides clashes then "The other restrictions" = "the ingredients to avoid" + "the restricted items" - "the sides clashes". Otherwise, that is if there are no Sides clashes, then "The other restrictions" = "the ingredients to avoid" + "the restricted items" - "the Dish clashes".
- The main dish Ingredients will be printed only if there are no Dish clashes AND no Sides clashes.
- Il the client ordered many servings, there will be a separate label for each serving.

**Comment by lamontfr** [comment]
@manumilou I made the changes. TODO layout on label, check and comments.

**Comment by lamontfr** [comment]
@manumilou I will make the changes corresponding to Revision 1 of requirements in PR #553.

**Comment by lingxiaoyang** [comment]
I think this has been merged in #568
