### ISSUE TITLE
Improve Ingredients filter / search

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#532]
### Expected Behaviour

- Ingredients filter / search should match a character string **contained** in the ingredient name.

### Actual Behaviour

- In Kitchen Count / Pick Ingredients page, the "Multiple Search Selection dropdown" only matches on character strings that start at the beginning of the ingredient name.

**Comment by manumilou** [comment]
Additional note: we are using the dropdown widgets provided by Semantic UI, in search mode: http://semantic-ui.com/modules/dropdown.html#search-selection. 
The behaviour described by @lamontfr is actually present in every search dropdown throughout the site. The search only applies to the beginning of the dropdown elements.
