### ISSUE TITLE
The organize route view does not display the changes made manually

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#533]
### Expected Behaviour

If I change the deliveries order on the _Organize route_ view, the order should be preserved and reloaded when I reload the page, or come back later.

### Actual Behaviour

The new order is properly saved, as it appears on the route sheets, but is not displayed on the map.

### Steps to reproduce

* Go to the kitchen count
* Make sure that every order is properly geolocated, as it will affect the _organize route_ view 
* Go the step 4 and select a route with more than 2 steps
* Change the order, by drag-and-dropping the letters in front of the client's name, in the right column
* Reload the page: the order has been resetted.

**Comment by lingxiaoyang** [comment]
I'm taking it.
