### ISSUE TITLE
Add a form to add a new note

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#536]
### Expected Behaviour

A simple form should be available to add new notes.
The author of the note should be automatically set to the logged-in user.
A _Add new note_ button should be displayed on the note list view.

### Actual Behaviour

It is only possible to create notes through the Django backend.

**Comment by lingxiaoyang** [comment]
I'm taking it.

**Comment by lingxiaoyang** [comment]
Preview:

![image](https://cloud.githubusercontent.com/assets/8630726/20802100/ef104526-b7b8-11e6-9bbb-f55d0425e081.png)

**Comment by lingxiaoyang** [comment]
@manumilou  Do we also allow adding a note in client management?

![image](https://cloud.githubusercontent.com/assets/8630726/20802849/5bac41f6-b7bb-11e6-9625-7186cb008576.png)

**Comment by lingxiaoyang** [comment]
Preview:

![image](https://cloud.githubusercontent.com/assets/8630726/20814458/b38fcc2c-b7e7-11e6-9ec2-45681d6884d4.png)

![image](https://cloud.githubusercontent.com/assets/8630726/20814476/c015a016-b7e7-11e6-9786-306c986c37c7.png)
