### ISSUE TITLE
Episodic clients should have a meals default per day

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#537]
### Expected Behaviour

Episodic clients should have one meal defaults per day, just as the regular clients.

### Actual Behaviour

Episodic clients only have one meals default. 

### Steps to reproduce

* Edit or create a new client
* Go the Preferences tab
* Select a delivery day

**Comment by lingxiaoyang** [comment]
1. front-end creation form
2. create multiple orders: multiple forms for days, default = main dish + dessert

**Comment by lingxiaoyang** [comment]
Preview 1: client editing
ongoing:
![image](https://cloud.githubusercontent.com/assets/8630726/20847624/f4b96446-b89c-11e6-9933-c97ffc831775.png)
vs episodic
![image](https://cloud.githubusercontent.com/assets/8630726/20847641/06407ac4-b89d-11e6-813e-254835b97cf0.png)

**Comment by lingxiaoyang** [comment]
Preview 2: client preference view
ongoing
![image](https://cloud.githubusercontent.com/assets/8630726/20847700/36e889e6-b89d-11e6-8380-b73ed2284d6e.png)
vs episodic
![image](https://cloud.githubusercontent.com/assets/8630726/20847676/23f7babe-b89d-11e6-83dc-a4cd5e02a8a4.png)

I removed the "on/off" icon for episodic.

**Comment by manumilou** [comment]
@lingxiaoyang Yes that's the idea. We could improve this view though because:

1. If no delivery or defaut exists for a given, we should probably not display the day at all. It does not bring much valuable information.
2. The on/off button is not user friendly, because it is not actually a button, and is not clickable. We should find another way to show that deliveries or defaut exists for the day. The fact of displaying the day (if we go forward with point 1) may already be enough.

**Comment by lingxiaoyang** [comment]
@manumilou  I added a "delivery type", and removed the on/off icon. Here's a preview. It seems to me a bit strange but I have to know your suggestions of what may be needed to change:

*Ongoing*:
![image](https://cloud.githubusercontent.com/assets/8630726/20891182/ad9458d6-bad7-11e6-9e73-8b8e2f019948.png)

*Episodic*:
![image](https://cloud.githubusercontent.com/assets/8630726/20891209/c4b3ed60-bad7-11e6-8973-b82a2509633a.png)

**Comment by lingxiaoyang** [comment]
@manumilou What color do you recommend for selected dates?
![image](https://cloud.githubusercontent.com/assets/8630726/20895969/b7cabf36-bae9-11e6-81b0-0ba4714366c0.png)

**Comment by manumilou** [comment]
Yellow or orange? Something that contrasts.

**Comment by lingxiaoyang** [comment]
@manumilou The "badge" orange?

![image](https://cloud.githubusercontent.com/assets/8630726/20904579/28a1bdee-bb0e-11e6-8ac8-a6ca86e7146c.png)
