### ISSUE TITLE
Only active clients should be included in the kitchen count

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#539]
### Expected Behaviour

Only orders of active clients should be included in the kitchen count.

### Actual Behaviour

If the status of a client is changed after his order has been created, it will still appear in the kitchen count.

### Steps to reproduce

* Generate orders for the kitchen count
* Review the orders
* Pick one order and change the client's status to PAUSED
* Review the orders
* The order should not appear in the list

**Comment by lamontfr** [comment]
I will look into this.

**Comment by manumilou** [comment]
@lamontfr I have already fixed this problem, I didn't see that you assigned it yourself. Sorry!

**Comment by lamontfr** [comment]
@manumilou No problem, I had not started to work on it.
