### ISSUE TITLE
Review the OWASP ZAP security report

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#551]
### Expected Behaviour

Every user inputs should be sanitized before used in a SQL request. The filters on the members list or the orders list allows users to input a client's name. This value should be checked. OWASP ZAP should not complain about the lists filters, unless the warnings are false-positive. 

### Actual Behaviour

Sous-Chef is using the query API of Django. No SQL query is built manually in this section, but still weird behavior occur when SQL injection is performed in the client's name text input.

### Steps to reproduce

* Go to the members list
* In the client's name text input, enter `John ' OR '1'='1'` 
* Two clients are found

Read the OWASP ZAP report attached.

[rapportZAP_sous-chef_1-12-16.html.gz](https://github.com/savoirfairelinux/sous-chef/files/631610/rapportZAP_sous-chef_1-12-16.html.gz)

**Comment by hsoft** [comment]
@manumilou no, we're not using the ORM everywhere. See https://github.com/savoirfairelinux/sous-chef/blob/73435e35e69d1655ef9780b27023c89639fd8144/src/order/models.py#L537

Very ugly...

**Comment by manumilou** [comment]
I never said the ORM was used everywhere. We are using manual SQL for the kitchen count generation. You can read the complete thread that lead to using manual SQL queries in this section, if you are interested: https://github.com/savoirfairelinux/sous-chef/issues/339.

**Comment by manumilou** [comment]
The ZAP report is now attached.

**Comment by hsoft** [comment]
@manumilou thanks for the link, interesting.

**Comment by hsoft** [comment]
I'm really tickled by this issue, so I *have* to look at it, but I'm still setting up the project. However, I'm looking and the issue, and then at the code... are you sure that it's really a security issue?

In our mock clients, two clients contain the substring "or". That would be consistent with the results we get...

**Comment by manumilou** [comment]
No I think you are right. The critical errors raised by ZAP seem to be false positive (the Cross-site scripting and the possible SQL injection). 
It should return 2 clients. I don't see which one is the third one ?

**Comment by hsoft** [comment]
Norma, Dorothy, St-Georges

**Comment by manumilou** [comment]
Indeed.
