### ISSUE TITLE
Kitchen Count: add filters on the review orders page

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#558]
### Expected Behaviour

In the first step of the Kitchen Count, the user should be able to filter by clients. An input text should be present.

### Actual Behaviour

No filters at all on the page.

![capture d ecran de 2016-12-08 14-49-08](https://cloud.githubusercontent.com/assets/212768/21025263/bd84c87c-bd55-11e6-9065-9b8481516c59.png)

### Steps to reproduce

* Click on the Kitchen Count menu item
* Click on **Generate Orders** (make sure to have the fixtures loaded before)

**Comment by lingxiaoyang** [comment]
A question on this: while filtering, do we remove the button "OK, I'm ready"? I think the button is a bit confusing when we don't have all orders in the list.

**Comment by ellmetha** [comment]
I'll start working on this issue. :wink:
