### ISSUE TITLE
The add order form should be unique 

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#560]
### Expected Behaviour

There should be only one form to add orders, and it should allow to add every kind of order item.
The user should be able to add a _Visit_ to an order, for instance.

### Actual Behaviour

The _Add order_ form is complex and not user-friendly but allow the user to add any kind of order items.
The _Multiple orders_ form is better, by allowing to add multiple orders at one time. But it does not allow the user to add other kind of order items than meal components. 

### Steps to reproduce

* Go to _Orders_
* Click _Multiple orders_
* Try to add a visit, or a delivery to the order

**Comment by lingxiaoyang** [comment]
@manumilou  Do we add more fields in batch add form? Like this:

![image](https://cloud.githubusercontent.com/assets/8630726/21054255/db7cbace-bdfa-11e6-826a-815b59f54202.png)

**Comment by lingxiaoyang** [comment]
@manumilou  How about toggles?
![image](https://cloud.githubusercontent.com/assets/8630726/21061305/b769d422-be19-11e6-8654-30e46c3c744f.png)

**Comment by lingxiaoyang** [comment]
@manumilou  And after the creation:

![image](https://cloud.githubusercontent.com/assets/8630726/21061396/3080e8f0-be1a-11e6-9f60-681f3aaf206c.png)

**Comment by manumilou** [comment]
@lingxiaoyang I like the toggles. 
One remark though: visit, pickup or deliveries, or any order items, should not appear in the order details view, if not selected.

**Comment by lingxiaoyang** [comment]
@manumilou   Ah, these two were selected, but it's showing every field as None. Do we change some values, or now showing them at all?

By the way, in `/src/order/models.py`, why `CHOICES_COMPONENT` is 'delivery'?
````
ORDER_ITEM_TYPE_CHOICES = (
    ('meal_component',
        _('Meal component (main dish, vegetable, side dish, seasonal)')),
    ('delivery', _('Delivery (general store item, invitation, ...)')),
    ('pickup', _('Pickup (payment)')),
    ('visit', _('Visit')),
)

ORDER_ITEM_TYPE_CHOICES_COMPONENT = ORDER_ITEM_TYPE_CHOICES[1][0]
````

**Comment by lingxiaoyang** [comment]
@manumilou  how about:
![image](https://cloud.githubusercontent.com/assets/8630726/21062972/48bb9e72-be21-11e6-8ec0-ef5f7f49aae3.png)

**Comment by manumilou** [comment]
Better!

Can we display the value rather than the key ? For instance:

* Meal Component rather than meal_component
* Delivery ( ... ) rather than delivery

**Comment by lingxiaoyang** [comment]
@manumilou  That's fixed.

On this page, when we click on "Update", it will go back to the original update order page (see image). Is it still acceptable, or should we use the same form (reuse batch creation)?

![image](https://cloud.githubusercontent.com/assets/8630726/21063549/29778fb4-be24-11e6-835a-7c174bf17fcc.png)

**Comment by manumilou** [comment]
Let's keep it like that for now.
