### ISSUE TITLE
The billing summary displays wrong number of main dishes

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#562]
### Expected Behaviour

The number of main dishes is different from the number of orders. When counting the main dishes, one should take into account the quantity of main dishes as well.

### Actual Behaviour

One order equals one main dish, on the billing summary.

See https://github.com/savoirfairelinux/sous-chef/blob/dev/src/billing/models.py#L110 et https://github.com/savoirfairelinux/sous-chef/blob/dev/src/billing/models.py#L113

### Steps to reproduce

* Create a few delivered orders in a given billing period
* Generate the billing
* View the summary

**Comment by lingxiaoyang** [comment]
Ah I see the problem.
