### ISSUE TITLE
Provide a Staff user profile, with read-only permissions

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#570]
### Expected Behaviour

A staff role / profile should exist. This role basically would have access to everything, but read-only.

### Actual Behaviour

No staff role exists. Only a super user.

**Comment by lingxiaoyang** [comment]
I'm interested in taking this issue. Would I simply follow the Django permission system?

https://docs.djangoproject.com/en/1.10/topics/auth/default/#permissions-and-authorization

**Comment by ellmetha** [comment]
@lingxiaoyang not sure if a full permission system is required here. But perhaps you could make use of the Django's ``User.is_staff`` field. :wink:

**Comment by lingxiaoyang** [comment]
@ellmetha  I'm not sure. It should depend on the client's future needs - whether he needs to customize staff's permission. 

@manumilou Could you explain more on it?
