### ISSUE TITLE
Order price: one side dish should be included in the meal's price

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#572]
### Expected Behaviour

1 main dish should come with 1 free included side dish, a side dish being a green salad, a fruit salad, etc ...

### Actual Behaviour

Every side dish is billed, with no regards to the number of main dishes.

### Steps to reproduce

* Create an order
* Save
* Look at the order detail

**Comment by lingxiaoyang** [comment]
@manumilou  Does it also mean that, in order creation form, the system default should also include a side dish? (so 1 main dish + 1 dessert + 1 side dish)
