### ISSUE TITLE
The "sous-chef" package should be renamed

### ISSUE THREAD

**Issue by ellmetha** [savoirfairelinux/sous-chef#575]
The Python package containing the project's settings is named "sous-chef". I think that "sous_chef" should be used instead. Some rationales:

* this is not compliant with the [PEP8 guidelines on the subject](https://www.python.org/dev/peps/pep-0008/#package-and-module-names) 
* you need a special syntax to import stuff from this package (https://github.com/savoirfairelinux/sous-chef/blob/d69933a28cea8125e029b1bd58b81df48343fcb7/src/member/tests.py#L30)
* nobody expects a module name with dashes or hyphens

:smile_cat:

**Comment by lingxiaoyang** [comment]
I agree!

**Comment by manumilou** [comment]
+1
