### ISSUE TITLE
Database optimization (foreign key field lookup)

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#581]
### Expected Behaviour

Don't make duplicate SQL queries in views.

### Actual Behaviour

Tested with Django Debug Toolbar. Most views make too much SQL queries that can be combined. Example:

1. On `http://localhost:8000/order/list/`, a page of orders require 71 queries with a lot of duplicates:

![image](https://cloud.githubusercontent.com/assets/8630726/21230516/410e3716-c2b3-11e6-9d94-4b92d7947fde.png)

2. On `http://localhost:8000/delivery/kitchen_count/`, our manual SQL query is very efficient, but there are 77 duplicates elsewhere that add up quite much time.

![image](https://cloud.githubusercontent.com/assets/8630726/21230702/c8504afc-c2b3-11e6-91ac-188b1c18f5aa.png)

It seems to me optimizable as the duplicates are mostly caused by foreign key field lookups, like `client.member.firstname`. Django has `select_related` and `prefetch_related` to deal with this.

### Steps to reproduce

* step 1: install django debug toolbar
* step 2: browse views

**Comment by lingxiaoyang** [comment]
More report on individual views: 

Tested with 1541 clients, 7190 orders, 14 staff notes, 2 billings at 00d5b5549aca144bf898bdb73722e53b7cc0a812

http://localhost:8000/member/list/
16,84 ms (75 requêtes including 67 duplicates )

http://localhost:8000/order/list/
26,66 ms (71 requêtes including 64 duplicates )

http://localhost:8000/note/
9,09 ms (39 requêtes including 30 duplicates )

http://localhost:8000/delivery/order/  (kitchen count)
20,56 ms (54 requêtes including 44 duplicates )

http://localhost:8000/billing/list/
3,51 ms (12 requêtes including 4 duplicates )

http://localhost:8000/member/view/608/information
3,64 ms (19 requêtes including 6 duplicates )

http://localhost:8000/member/view/608/preferences
9,89 ms (48 requêtes including 30 duplicates )

http://localhost:8000/member/view/608/orders  (louise dallaire – 48 orders)
16,24 ms (65 requêtes including 50 duplicates )

http://localhost:8000/member/608/update/basic_information/
4,41 ms (19 requêtes including 8 duplicates )

http://localhost:8000/member/608/update/address_information/
5,34 ms (20 requêtes including 8 duplicates )

http://localhost:8000/member/608/update/payment_information/
4,97 ms (22 requêtes including 13 duplicates )

http://localhost:8000/member/608/update/dietary_restriction/
9,44 ms (32 requêtes including 14 duplicates )

http://localhost:8000/member/608/update/emergency_contact/
5,54 ms (22 requêtes including 12 duplicates )

http://localhost:8000/order/view/1117/
3,97 ms (15 requêtes including 5 duplicates )

http://localhost:8000/order/update/1134/
597,58 ms (1554 requêtes including 1545 duplicates )

http://localhost:8000/order/create/batch
31,08 ms (142 requêtes including 134 duplicates )

http://localhost:8000/delivery/meal/
11,65 ms (31 requêtes including 20 duplicates )

POST http://localhost:8000/delivery/meal/
21,34 ms (49 requêtes including 39 duplicates )

http://localhost:8000/delivery/kitchen_count/
40,19 ms (109 requêtes including 98 duplicates )

http://localhost:8000/delivery/routes/
13,60 ms (20 requêtes including 12 duplicates )

http://localhost:8000/delivery/route_sheet/1/
9,89 ms (21 requêtes including 12 duplicates )

http://localhost:8000/note/add/
348,51 ms (1551 requêtes including 1543 duplicates )

http://localhost:8000/billing/view/5/
834,88 ms (1970 requêtes including 1951 duplicates )

http://localhost:8000/billing/view/5/orders/
1627,90 ms (7940 requêtes including 7932 duplicates )

http://localhost:8000/billing/add/
20,57 ms (71 requêtes including 64 duplicates )

POST http://localhost:8000/billing/create/?delivery_date=2016-10
1990,43 ms (4638 requêtes including 4632 duplicates )

**Comment by lingxiaoyang** [comment]
I'll work on this.

**Comment by lamontfr** [comment]
@lingxiaoyang Thank you for finding this problem. I had heard of the Django Debug Toolbar but I had not used it yet. I will use it from now on. I have found the causes of the repeated queries in http://localhost:8000/delivery/kitchen_count/ specifically, and have started to fix them, since I am currently working on improving the Report and Meal Labels contents.

**Comment by lingxiaoyang** [comment]
@lamontfr That's cool! I'll leave it to you.

@manumilou  As we two have mentioned the Debug Toolbar, do we consider a PR only to add the Toolbar in settings, for easier **1.** verification of PR   **2.** future optimization  **3.** working together?

It will only require:

1. In `requirements.txt` add `django-debug-toolbar`
2. `INSTALLED_APPS += ['debug_toolbar']`
3. `MIDDLEWARE` needs to add `debug_toolbar.middleware.DebugToolbarMiddleware`.
4. In `urls.py`, add http://django-debug-toolbar.readthedocs.io/en/stable/installation.html#urlconf:
````python
from django.conf import settings
from django.conf.urls import include, url

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
````


As said the documentation, the Debug Toolbar only works with `DEBUG=True` so we can assume a quite small overhead in production.
