### ISSUE TITLE
Cannot select meals prefs for multiple orders anymore

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#582]
### Expected Behaviour

On the order add form, I should be able to select the meals preferences for each dates I selected.

### Actual Behaviour

I can select the meals prefs only for the first date I selected.

![capture d ecran de 2016-12-15 11-09-14](https://cloud.githubusercontent.com/assets/212768/21231725/4e163a86-c2b7-11e6-94a6-8945d10a4c4e.png)

### Steps to reproduce

* Go to _order/create/batch_
* Select a client
* Select multiple dates
* See the meal preferences forms

**Comment by lingxiaoyang** [comment]
I see why...
