### ISSUE TITLE
Too many information for the payment types

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#584]
### Expected Behaviour

The payment type should be optional in the client's creation form.
The values should be:
- EFT
- Credit
- 3rd Party

### Actual Behaviour

The payment type is mandatory in the client's creation form.
The values are:

- Check
- Cash
- EFT
- Credit

### Steps to reproduce

* Go to the client's creation form
* Go to the _Payment_ tab

**Comment by fpeyre** [comment]
I will take it
