### ISSUE TITLE
Deleting a route should not delete associated clients

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#585]
### Expected Behaviour

I should be able to delete a route without deleting every clients assigned to it. 
The clients should just have an unassigned route.

### Actual Behaviour

Deleting a route deletes every clients assigned to this route.

### Steps to reproduce

* Go to the Django backend
* Select the Routes model
* Try to delete a route (ex: McGill West)

**Comment by fpeyre** [comment]
I will take it

**Comment by fpeyre** [comment]
Hmm after a quick search, it is the normal behaviour of django ( https://groups.google.com/forum/#!topic/django-users/jt3wHS3_gSs )
I can make a fix for this case, but maybe we must check if this behaviour could be a problem in another case
