### ISSUE TITLE
The admin should be able to add a bill's delivery item at the route sheets step

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#599]
### Expected Behaviour

When organizing a route sheet, the user should be able to specify that a client will receive a bill as well as his meals.

![capture d ecran de 2016-12-21 06-23-47](https://cloud.githubusercontent.com/assets/212768/21387566/2614e224-c746-11e6-9b10-9e0122a15ea3.png)

Receiving a bill  = adding a new order item, of type _delivery_.

The information must appear on the printable version as well.

### Actual Behaviour

To add a bill's delivery, the user has to go to the order view, update it, add a new delivery type order item, then return to the kitchen count.

**Comment by lingxiaoyang** [comment]
I'll work on this.

**Comment by lingxiaoyang** [comment]
Depend on #570 for admin permission.
