### ISSUE TITLE
Implementing an intuitive and intelligent way to handle delivery routes

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#6]
## Objectives
- Use of interactive maps, tightly integrated to the route configuration interface, to assist routes creations: OpenStreetMap, Google Maps
- Drag and Drop support
- Persistent customer order in routes
- Use of route optimization algorithm
### Current problems
- Can be complicated to create an optimal route
- No drag and drop support
- Customer order can be lost if its deliveries are stopped for a while

**Comment by rjacquemin** [comment]
Take a look at GeoDjango and PostGIS.
GeoDjango will give you the ability to store geo informations and do distance lookups.

see below 
https://www.youtube.com/watch?v=Dfd5lzrz7ps
https://www.imagescape.com/blog/2011/09/21/geo-django-quickstart/

**Comment by rjacquemin** [comment]
FYI:
Geodjango is only fully compatible with PostgreSQL.
https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/#requirements

If the map feature is important  for the app it  might be better to use postgresSQL

**Comment by rjacquemin** [comment]
Without geo-django and the postgresSQL 

we can use leaflet with routing plugin 
http://www.liedman.net/leaflet-routing-machine/

**Comment by manumilou** [comment]
Mapbox is also a possible solution: https://www.mapbox.com/.
It provides a Geocoding API and a directions API as well.
Not open-source though, but free under 50,000 map views / mo.
