### ISSUE TITLE
Check that every string is translatable

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#60]
For a Python string to be translatable, it needs to be pass through the _() function.

Some strings, that should be translatable, may not respect that. They should be corrected.

**Comment by RignonNoel** [comment]
In template the function is : 
```{% trans 'my text' %}```

**Comment by maximest-pierre** [comment]
We are waiting for a convention for the writing styles. To discuss at the next meeting.

**Comment by maximest-pierre** [comment]
I found some strings that are not translated inside the login.html

**Comment by RignonNoel** [comment]
We change the process : #121
Check every string is translatable with real english version in the code.
