### ISSUE TITLE
Enhance client list view filter: multiple statuses

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#613]
### Expected Behaviour

Client list view (in list format): http://localhost:8000/member/list/?display=list

Santropol would like to separate the client list according to delivery route, where only "active" and "pause" clients are shown.

### Actual Behaviour

At present, the filter only allows one status to be selected, and it is not possible to select both "active" and "pause" at the same time.

### Steps to reproduce

NA

**Comment by manumilou** [comment]
@lingxiaoyang You can filter by route right now on the client list. But, yes, it could be nice to be able to filter with multiple statuses.

**Comment by lingxiaoyang** [comment]
@manumilou  Ah, I didn't see the "route" filter...

OK, I'll change this issue.
