### ISSUE TITLE
Define "status" of a staff note

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#614]
### Expected Behaviour

A staff note should have a "status" field (values to be provided by Santropol). This field should also be editable.

### Actual Behaviour

A staff note only has "Priority" as normal or urgent. It is not possible to change the priority after its creation.

### Steps to reproduce

NA

**Comment by lingxiaoyang** [comment]
@manumilou  Do we remove the "Priority" field and replace it with "Status"?

**Comment by manumilou** [comment]
@lingxiaoyang We can keep the Priority field for now. It still could be useful. Did we receive the categories yet ?

**Comment by lingxiaoyang** [comment]
@manumilou  I have no idea.

**Comment by lingxiaoyang** [comment]
The category list:

- Follow-up needed

- No Charge
- Orders/Cancellations

- Comments (no actions needed)
- Kitchen Comments

- Stay late notes
- Payment reception
