### ISSUE TITLE
Staff note list view filter should support "date" field

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#615]
### Expected Behaviour

In staff note list view (http://localhost:8000/note/?is_read=0), the user should be able to filter on "date".

@manumilou  What value is needed here? A single date would be ok or it has to support a period?

### Actual Behaviour

There is no "Date" field in the list filter.

### Steps to reproduce

NA

**Comment by manumilou** [comment]
@lingxiaoyang  A single date would be fine.
