### ISSUE TITLE
Add a dashboard element that lists the global number of stops by route

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#616]
### Expected Behaviour

On the dashboard, there should a block that lists, by route, the number of clients (stops) registered.

### Actual Behaviour

No easy to way to know which route is overloaded or underloaded.

**Comment by lingxiaoyang** [comment]
@manumilou If showing the client numbers directly in a table, would it be too weird?

![image](https://cloud.githubusercontent.com/assets/8630726/21779737/e5d3cb2c-d676-11e6-9f11-77f2d49b328a.png)

Or perhaps we implement a pie/donut chart for this, as discussed in issue #225 ?

**Comment by manumilou** [comment]
@lingxiaoyang No, it's pretty good. We should fix the layout a little, maybe by allowing a vertical scrolling.
We also could use the label element of Semantic UI (http://semantic-ui.com/elements/label.html) for the number of clients by route.

**Comment by lingxiaoyang** [comment]
@manumilou  How about this one?

![image](https://cloud.githubusercontent.com/assets/8630726/21785531/eaff0334-d68d-11e6-9760-e3fa575542e6.png)

**Comment by manumilou** [comment]
It's kind of messy and harder to read.

**Comment by lingxiaoyang** [comment]
@manumilou  Perhaps we show a modal for displaying all the route information and provide a button in the footer to trigger it?

Another question: should the client number here only include active clients, excluding inactive clients?

**Comment by manumilou** [comment]
The clients number should include active and paused clients.
