### ISSUE TITLE
Member quick search seems doesn't work fine. Search results cached.

### ISSUE THREAD

**Issue by aaboffill** [savoirfairelinux/sous-chef#626]
### Expected Behaviour

Show a list with the members that match with the introduced query in the member search field. Inside the `Client` form, in order to include a `Member` as referent.

### Actual Behaviour

The `Semantic`'s search component save in cache the first search's result, and after, the same first result will be received no matter what is the introduced query.

### Steps to reproduce

* Click on `Client` item menu.
* Select to include a new `Client` or find an existing `Client` in order to modify it.
* Go to the `Referent` tab and try to find different members using several queries in the quick `Member` search field. "No matter what is the introduced query, the result will be always the same."

**Comment by aaboffill** [comment]
This is the code to make the ajax request to get the member list using `semantic`:
`
$('.ui.search').search({
        apiSettings: {
            cache : 'local',
            url: $search_url + '?name={query}',
        },
        minCharacters : 3,
    });
`

Is necessary set the cache to `false` in order to fix the bad behavior.

**Comment by aaboffill** [comment]
I found other problem related with the `Member` quick search. The filter doesn't work fine for other reason. By default, `semantic`'s search component use the URL to send the ajax request from `data-url="urlvalue"`, added to the search `HTML` component, We can see it  [here...](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/member/templates/client/partials/forms/referent_information.html#L5)

This URL override the URL set in the `JavaScript` definition [here...](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/frontend/js/member.js#L138) 

For that reason, the query value to filter the `Member` list in the Client form will never arrive, the param 'name' doesn't exist in the request because the called URL is `member/search` instead of `member/search?name=somevalue`.

To fix that is necessary to move to other `HTMl` element the attribute `data-url="urlvalue"`

**Comment by aaboffill** [comment]
@manumilou if everything is OK for your side, I can add the solution to fix the problems.

**Comment by lingxiaoyang** [comment]
@manumilou  What we're using here is a semantic ui category search. Is it possible to replace it with ui search dropdown? We're using the dropdown elsewhere such as notes, kitchen count, etc. 

Another possible interaction problem with ui category search is that, when the field is empty, clicking on the field won't popup the list of clients. The user has to enter something to see the list.

@aaboffill  With ui search dropdown, it'll also be much easier to put the list into Django template (as `<option>`s). Then no need to do the AJAX!

Now:
![image](https://cloud.githubusercontent.com/assets/8630726/22078559/6729d20a-dd86-11e6-8a1c-57875c8f4b4e.png)

UI Search Dropdown example:
![image](https://cloud.githubusercontent.com/assets/8630726/22078581/7990adce-dd86-11e6-8b8a-37fb2db4c8db.png)

**Comment by aaboffill** [comment]
I think that to decide what is the better option between `ui category search` and `ui search dropdown`, is good to know how much the `Member` list can grow. If in the future, the `Member` list become in a big list, is better keep the `ui category search`, in other circumstance `ui search dropdown` is a good option.
I have little knowledge about `Sous-chef` project, maybe @manumilou  and @lingxiaoyang could help me to know if the `Merber` list will be a big or an small list. 
Anyway I have the solution to fix the problems related to `ui category search`.

**Comment by lingxiaoyang** [comment]
@aaboffill  You have a good point. The dropdown is a little bit laggy now in 'Add a Note' view above, and it only includes a part of clients (active and paused?), I think.

Yes, there could be a large number of Member objects.
