### ISSUE TITLE
Python dependencies are outdated

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#632]
### Expected Behaviour

Keep them up-to-date and make sure everything functions well.

### Actual Behaviour

From versioneye:
![image](https://cloud.githubusercontent.com/assets/8630726/22129735/d1c20872-de75-11e6-9f58-80e5d4e52d65.png)

### Steps to reproduce
N/A

**Comment by lingxiaoyang** [comment]
Notes:

`mysqlclient` may possibly be removed from the list. We don't have a code file explicitly referencing this library.

`fake-factory` is deprecated in favor of `Faker`, also not explicitly depended by sous-chef. An update of factory_boy should let remove it.

And also, in `requirements.txt`, we should favor automatic update of minor version, such as:

    Django>=1.10,<1.10.99

as minor versions are not supposed to change programming APIs but to offer security updates/bugfixes.

**Comment by lingxiaoyang** [comment]
Todos:

(tl;dr: major change required is the django-filter update. Minor issue is related to CAPhoneNumberField in django-localflavor that is deprecated now. All other updates are fine.)


### factory_boy 2.7.x->2.8.x

[Changelog](https://factoryboy.readthedocs.io/en/latest/changelog.html)

No change in functionalities.


### django-formtools 1.0->2.0

[Changelog](https://django-formtools.readthedocs.io/en/latest/changelog.html)

(nothing to do) Dropped support for Django 1.7 and Python 3.2 on Django 1.8.


### django-filter 0.13.x->1.0.x

[Changelog](https://github.com/carltongibson/django-filter/blob/develop/CHANGES.rst)

It has in between 0.14.x and 0.15.x

- [ ] [Needs migration](http://django-filter.readthedocs.io/en/latest/guide/migration.html)


### django-annoying 0.9.x->0.10.x

No official changelog. [Refer to allmychanges.com](https://allmychanges.com/p/python/django-annoying/)

> 0.10.1: Fix render_to_response deprecation warning for django >= 1.9
> 0.10.2: fix: Fix persisting data to strings for the JSONField after a Django 1.9 change.
> 0.10.3: fix: Try to fix the previous fix.

Nothing to do.


### django-leaflet 0.18.x->0.19.x

[Changelog](https://github.com/makinacorpus/django-leaflet/blob/master/CHANGES)

> 0.19: Added ``leaflet.admin.LeafletGeoAdminMixin``, useful for stacked or tabular inline forms (thanks @KostyaEsmukov, @Xowap)

Nothing to do.

### django-localflavor 1.3->1.4

[Changelog](https://django-localflavor.readthedocs.io/en/latest/changelog/)

> Modifications to existing flavors:
> 
>     Enhancements of localflavor.br.forms.BRCNPJField (gh-240 gh-254).
>     Fixed century bug with Kuwait Civil ID verification localflavor.kw.forms (gh-195).
>     Allow passing field name as first positional argument of IBANField. (gh-236).
>     Fixed French FRNationalIdentificationNumber bug with imaginary birth month values. (gh-242).
>     Fixed French FRNationalIdentificationNumber bug with corsican people born after 2000. (gh-242).
>     Fixed the translation for US state ‘Georgia’ from colliding with the country ‘Georgia’ (gh-250).
>     Fixed the styling errors and enabled prospector (gh-259).
>     Allow AU ABN value with spaces to validate (gh-266 gh-267).
> 
> Other changes:
> 
>     Drop support for Django 1.7 (gh-218).
>     Ensure the migration framework generates schema migrations for model fields that change the max_length (gh-257). Users will need to generate migrations for any model fields they use with ‘makemigrations’.
>     Lazily generate US_STATES, STATE_CHOICES, and USPS_CHOICES (gh-203 gh-272).

- [x] **Deprecated Phone Number fields (gh-262).**

We're using CAPhoneNumberField in sous-chef.
Check [this issue](https://github.com/django/django-localflavor/pull/262) for this change in django-localflavor. 
This will be created as another issue. But for current dependency update, it's fine.

>     Bumped versions of requirements for testing (gh-274).
> 

### rules 1.1->1.2

[Changelog](https://pypi.python.org/pypi/rules#changelog)

1.2.0:

>         Added logging to predicates
>         Added support for Django 1.10
>         Fixed undesired caching in is_group_member factory

Nothing to do.

**Comment by KostyaEsmukov** [comment]
Dear @lingxiaoyang , could you please not `@` mention people for no reason? Thanks.

**Comment by lingxiaoyang** [comment]
@KostyaEsmukov

I'm sorry man for the trouble! Have a nice day!
