### ISSUE TITLE
[Dashboard] Display birthdays of the week

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#649]
### Expected Behaviour

The dashboard element **Happy Birthday** should display birthdays of the week.

### Actual Behaviour

The dashboard element **Happy Birthday** displays birthdays of the day only.

### Steps to reproduce

* Create a client whose birthday is tomorrow
* Check that his name does not appear on the homepage

**Comment by lingxiaoyang** [comment]
Merged in #661
