### ISSUE TITLE
Favicon is missing 

### ISSUE THREAD

**Issue by rjacquemin** [savoirfairelinux/sous-chef#650]
### Expected Behaviour

Sous-chef logo should be displayed in the favicon placeholder

### Actual Behaviour

Default favicon is displayed
see attached screenshot

### Steps to reproduce

* loggin 
* check favicon

<img width="892" alt="souschef-favicon" src="https://cloud.githubusercontent.com/assets/12820060/22273262/a5eca18e-e26d-11e6-97f3-f9851a0bf531.png">

**Comment by lingxiaoyang** [comment]
Merged in #660. Closing.
