### ISSUE TITLE
Edit Button in Billing Module 

### ISSUE THREAD

**Issue by rjacquemin** [savoirfairelinux/sous-chef#652]
### Expected Behaviour

Edit button is not usefull . 
It should be hidden or remove. 

### Actual Behaviour
Edit button is displayed but just redirect on same page

<img width="910" alt="billing_editbutton" src="https://cloud.githubusercontent.com/assets/12820060/22273242/8b5fa762-e26d-11e6-8bb7-1dc2b8ee0fad.png">

### Steps to reproduce

* step 1
* step 2
* ...

**Comment by lingxiaoyang** [comment]
Merged in #659. Closing.
