### ISSUE TITLE
It is not possible to create orders for Paused clients

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#686]
### Expected Behaviour

As a system administrator or staff member, I should be able to create new orders for any types of clients.

### Actual Behaviour

From what I tested, it is possible to create orders for Paused clients, but it needs to be confirmed.

### Steps to reproduce

* Change a client to Paused
* Try to create an order

**Comment by lingxiaoyang** [comment]
I confirm this issue. The paused clients are not displayed in the order creation form.
