### ISSUE TITLE
Skipped command message is error-prone

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#689]
### Expected Behaviour

As an administrator or a staff member, when I create orders for a given client, there is no indication that I will be creating an order for a day where an order already exists. I only get a message saying that an order has been skipped once I saved. 
The orders creation form should inform me that an order already exists for the selected days and eventually asked me if I want to override it or edit the existing one.

### Actual Behaviour

When an order is already created for a given day, the system will refuse to create an other order for this day. This is the desired behavior for the scheduled tasks to avoid order overrides. But I should be able to manually override an existing order through the order's creation form.

### Steps to reproduce

* Create an order for a client for a given day
* Use the order creation form to create an other order for the same day
* Save

**Comment by peakwinter** [comment]
@manumilou Should an existing order overridden in this way be...

1. flagged as 'Cancelled',
2. flagged as 'Overridden' (necessitating the creation of a new order status flag), or
3. simply deleted?

**Comment by manumilou** [comment]
@peakwinter Flagged as Cancelled would be the best solution I think. What's your take on that?

**Comment by peakwinter** [comment]
@manumilou I guess it depends on what usually would warrant this sort of change; is the user overriding an order because the user expressly cancelled it, or because the initial order was created in error?

**Comment by manumilou** [comment]
Usually, it will happen because, as orders are generated in advance (30-90 days) according to client's defaults (ongoing clients only), some orders need to be modified / cancelled / added. The use case here is the following:
- for a given ongoing client, his orders are generated a month in advance
- for a given day, the client wants to modify or add an order. The staff member uses the Add orders form to do that, which does not provide any indication on whether or not an order already exists

The best way to handle this would be to hightlights days on the calendar for which an order has already been created, and allow to load it in the form and modify it.

**Comment by JeanFrancoisFournier** [comment]
When trying to enter an order on a day a specific clients already has an order, I should be alerted by the system and given the choice of either replacing the pre-existing order with the one that was just inputed or cancel this action.

It would be nice to see the actual content of both orders when making the choice between the old order and the new one. ie:
***
The client already has an order scheduled for this day. 
Would you like to replace this order:
1 Meal and 1 Fruit salad - Created January 10, 2017
with this order:
2 Meals and 2 Green salad - Created March 23, 2017
REPLACE - CANCEL

**Comment by lingxiaoyang** [comment]
@peakwinter

**Comment by peakwinter** [comment]
Notes to self:

* Move confirmation modal and `override_dates` operations to occur at order submission rather than date selection
* Obtain and display existing meal summary in the modal
