### ISSUE TITLE
Determine the sequence of all clients in a route even when they have no delivery

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#691]
### Expected Behaviour (changed on 2017-03-23 - see comment)
- For a route, allow the CM to optimize, modify and save the sequence of all (active, pending or paused) clients in the route, whether they have a forthcoming delivery or not. This becomes the "default order" for the route. This will require a new main menu entry, because it is not related to the daily kitchen count. However, the same UI and most of the logic of "Route / Organize" can be reused.
- When a new client is created or a client is resumed from a "stop: contact/no contact" status, ~~the CM has to positioned him(her) in his(her) route sequence~~ the client is positioned to the end of the list by default.
- On a day where there are deliveries on this route, the stops with meals will be ordered as per the default (except for the gaps for clients having no delivery on that day), and the CM will still be able to alter the sequence temporarily for the current day if necessary.

### Actual Behaviour

- The CM can optimize and make changes to the sequence of clients having meals to be delivered in a route for a given day.
- On a another day after that, when the CM displays the sequence for the latter route, only clients that have a meal everyday are still in the correct position in the sequence.
- This means that when a client has no meal delivered on a given day, the system forgets the client's proper position and the next day on which he has a meal, he will appear at the end of the sequence. This will oblige the CM to move again the client back to his place in the sequence, which is time consuming.

**Comment by lamontfr** [comment]
The issue was discussed with Jean-François on 2017-03-22 and it was decided to change the title and expected behavior.
The old version was :
**Title** "Remember the adjusted sequence of clients in a route even when they skip some delivery days".
**Expected behavior** : 
- Allow the CM (client manager) to adjust the ordering of the stops for the clients belonging to a route on a day where they have a delivery and then save the sequence.
- Later, when a client on this route has no delivery on at least a day and then resumes in the future, he should be in a position which is as close as possible to the position he had the last time the sequence was saved with him in it.

**Comment by JeanFrancoisFournier** [comment]
This "new main menu entry" should allow the CM to view/modify/save the route default order for any individual routes. This will reflect the route order of an hypothetic delivery day where every client (active ongoing, active episodic, paused and pending) would be receiving a meal.

The positionning of a new/resuming client in this "Route order default" should not be an additional step in the new client creation form.

New and resuming clients could be placed at the end of their "Route default order" while awaiting positionning by the CM

**Comment by lingxiaoyang** [comment]
I'll try to work on this.

**Comment by lamontfr** [comment]
Great ! BTW I'm making good progress on issue #696.

**Comment by lingxiaoyang** [comment]
Implementation plans (also fixes #612):

1. Keep the `member.Route` model as it is now, but alter the definition of `client_id_sequence` field - it will be a JSON list storing the "default" order for all active/paused/pending clients.
2. New model `member.DeliveredRoute` keeps track of route configurations on each delivery day. It has four fields:
  - `route`: Foreign key to member.Route
  - `date`: Date object
  - `vehicle`: Vehicle for the particular day
  - `client_id_sequence`: A JSON list containing the configured client sequence.
  - `merged_routes`: A JSON list containing the IDs of merged routes. If a merge didn't happen, it should be empty.
  - `comments`: additional comments

3. New views:
  - Route list view: List all routes and related information
  - Route detail view (parameter: route ID): Allow editing of route information (name, description and vehicle), and client sequences (allow explicit auto-planning based on euclidean distances). Provides links to delivered route views.
  - Delivered route view (parameters: route ID, date): Allow only viewing of the client sequences.

4. Change of existing views:
  - Route organize in kitchen count: Allow merging/unmerging routes. Client sequence edits will be redirected to `member.DeliveredRoute` instance.
  - If a client is stopped or deceased, remove him/her from the default sequence. Thus when we resume the client, we will have to perform the repositioning.

@lamontfr  We may finally need to merge this issue and #696.

**Comment by lingxiaoyang** [comment]
Ideally we should have a separate `Route` app and move all related functionalities there, but it implies too many changes in our current codebase. If we feel necessary, we may do that in 2.0.

**Comment by lamontfr** [comment]
@lingxiaoyang I will ask Jean-François about whether merging / unmerging routes is essential to have in order to use SousChef exclusively (without Feast).

**Comment by lingxiaoyang** [comment]
@lamontfr  Sure, thank you!

**Comment by lamontfr** [comment]
@lingxiaoyang I got an answer from Jean-François, and he prefers to postpone the development of issue 612 (route merging) until Milestone 2. The SRoulant staff is quite eager to get SousChef in real production and they chose the essential issues that we should deliver for milestone 1.1. You are in cc. of my reply to him. Your proposed plan is elegant but I think a two step approach is indicated here to favor "customer satisfaction".

Can you please split the implementation plan in two phases, the first one being for issue 691 based on Jean-François's comment on March 24th above ?

**Comment by lamontfr** [comment]
@lingxiaoyang 
Here are some thoughts about this issue :
- With the current system (Feast), SantropolRoulant (SR) have no route
  optimization, no geolocalization and no map.
- When a new client arrives, they look at Google Maps, then choose a route to
  put him in and then place him in a fixed position in the route sequence in
  Feast; which is for any status of client, irrespective of the day.
- On a delivery day, Feast prints the route sheet for clients having a
  delivery in the fixed order. Then the SR staff look at specific constraints
  (i.e. a client must get his meal earlier because he has to leave at 12:00 go
  to see the doctor) and change the order by writing (1, 2, 3 ...) manually
  next to each client on the printed sheet.
- SousChef currently adds much more functionality for the routes, and the map
  is very useful. But SR do not yet use optimization nor vehicle selection.
- So we need to allow SR time to live with SousChef for a while and
  progressively appreciate the features so that they can tell us how to adjust
  them optimally for their processes.
- Finally, IMHO, I suggest that we do not yet modify the current route
  mechanism, but simply add the "Default Route Sequence" as a decoupled
  feature. We could simply have a button in "Organize route" thay says "Use
  Default Sequence" which would then reorder the clients in the day's route
  according to the saved default. After this has been tested and used by SR
  for a while (months), we will obtain their feedback, write down their
  requirements which will include route merging / unmerging, and properly
  Refactor all the code in a new app.
- What do you think ?

**Comment by lingxiaoyang** [comment]
@lamontfr  Thank you for the contact! I'll postpone the merging of routes. It'll simply be a removal in my proposed plan and my progress is far from that point.

**Comment by lingxiaoyang** [comment]
**Progress: "Route" menu finished.**

List view:
![image](https://cloud.githubusercontent.com/assets/8630726/24772811/bfdd73ce-1ae0-11e7-9fda-0b3322985ba8.png)


Detail view:
![image](https://cloud.githubusercontent.com/assets/8630726/24772835/d4745320-1ae0-11e7-979f-0ce069fe268a.png)

Edit view:
![image](https://cloud.githubusercontent.com/assets/8630726/24772906/037c4204-1ae1-11e7-88f3-1dc7cdeb5af6.png)

**Todos**: 1. automatic sequencing by euclidean distance on one click; 2. unit test; 3. fix the route organization in kitchen count.
