### ISSUE TITLE
Improve printed route sheets contents and formatting

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#696]
### Expected Behaviour
- Print all the routes in one operation (one click).
- Each route should start on a odd numbered new page (see issue #611 ).
- The information block on a client stop on the route sheet should never be split by a page break.
- The font size should be large enough (Helvetica 10 or above) to be clearly legible when printing.
- The SRoulant address and contact information is required in the page layout template.
- PDF file generation would be desirable (see also comment on March 11th in #611).

(This is based on requirements given by Jean-François on 2017-03-17)

### Actual Behaviour
- The layout of the global routes printout http://localhost:8000/delivery/routes/?print=yes is too basic and is not usable by the delivery volunteers therefore the CM has to print each route separately.
- Using the print route sheet button in http://localhost:8000/delivery/route_sheet/1/, printing font size is too small.
- Page breaks on odd numbered pages are not supported by the browsers.

**Comment by JeanFrancoisFournier** [comment]
Precision: 
1# The font size should be at least 12 (right now, our route sheets are using 12 for text and 14 bold for client's names)
2# The SR logo, name, address and phone number should be clearly indicated in a size 12 font
3# A header indicating to the volunteers that the informations on that route sheet are confidential should be included as:
"Ce document contient des informations CONFIDENTIELLES"
"This document contains CONFIDENTIAL information."

**Comment by JeanFrancoisFournier** [comment]
A PDF file generation, much like the one used in printing the kitchen count form, would be preferable

**Comment by kousu** [comment]
Hi there, great work getting this in.

There's a nit I would like to point out, and reopen this bug for. While the Route Sheets button on the main overview makes PDFs

![screenshot from 2017-08-15 19-42-04](https://user-images.githubusercontent.com/987487/29341468-7c1cf96a-81f2-11e7-9d5b-f561a9b3c8c4.png)

The button on the per-route page still just calls `document.print()`:

![screenshot from 2017-08-15 19-40-06](https://user-images.githubusercontent.com/987487/29341334-a943710e-81f1-11e7-8dd1-9602ccf64992.png)
