### ISSUE TITLE
Meal defaults and Meal schedule should be separate elements in the UI

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#700]
### Expected Behaviour
- Meal defaults and meal schedule are two different concepts and the UI should reflect this.
- Irrespective of delivery type (ongoing and episodic) the client preferences should always show the meal defaults, that is **what** the client said he wants in **his** meal for specific weekdays.
- For an ongoing delivery type only, the client preferences should also show the meal schedule, that is **when** (= on which weekdays) he wants **his** meal delivered.

(This is an addition to issue #688, based on requirements given by Jean-François on 2017-03-17)
### Actual Behaviour
- The UI only offers Meal schedule which is confusing.

**Comment by JeanFrancoisFournier** [comment]
This issue should be tagged as Milestone 1.1 because of it being so closely related to issue 688
