### ISSUE TITLE
Behaviour inconsistent in client selection on the New Orders page

### ISSUE THREAD

**Issue by peakwinter** [savoirfairelinux/sous-chef#710]
### Expected Behaviour

Selecting a client on the new orders page should either:

 * complete an AJAX GET request to obtain necessary information from the API, or
 * complete a POST + full page reload to obtain necessary information, as if selecting a new delivery date,

but not both.

### Actual Behaviour

On client selection, a GET request is fired [here](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/frontend/js/order.js#L82) which tries to obtain information about meal defaults but in reality appears to do nothing. This AJAX call enters into conflict with the one [here](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/frontend/js/multidatespicker.js#L64), which is never actually executed due to a bug.

We should decide which of these calls to keep and fix, and which one to scrap.

### Steps to reproduce

* Open developer tools
* Click Orders > New Order
* Select a client
* Observe the GET request being fired, but the server returns an XHTML document instead of the expected JSON, etc etc

**Comment by lingxiaoyang** [comment]
@peakwinter  It would be my problem of not cleaning the old code (AJAX) when implementing the new feature (HTML form). You may delete the previous AJAX code I think, which returns an XHTML page and doesn't work either.

Do you think it's necessary to have two files order.js and multidatespicker.js? Although the MultiDatesPicker object is only used in the order batch create form, it essentially belongs to the order module in regards to functionality.

**Comment by peakwinter** [comment]
@lingxiaoyang The trouble is that even if I remove that AJAX code and fix the part that sends a POST on client change, it still doesn't work (well) and merits additional investigation. Which is why I've filed the bug :)

I don't believe we need two files, it adds a bit to the confusion. Unless mutlidatespicker.js is dedicated to creating a reusable "date picker" component that can be used in multiple places in the UI, which does not appear to be the case here.

**Comment by lingxiaoyang** [comment]
@peakwinter  I didn't understand: which doesn't work well?

**Comment by peakwinter** [comment]
@lingxiaoyang The function [here](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/frontend/js/multidatespicker.js#L64) that is supposed to fire the POST request, process the new info and reload the page. It doesn't appear to set the contents of the client dropdown, should be tested to ensure it loads meal defaults properly if dates are already selected, etc.

**Comment by lingxiaoyang** [comment]
@peakwinter  Ah I see. In fact, it works when you have selected some dates, but when the form is at initial state (empty), this event is not fired for some reason...

**Comment by lingxiaoyang** [comment]
@peakwinter I see why. There's an error in the console 'Error: Empty array of dates received.' when the form is empty, and then the script is interrupted.

**Comment by lingxiaoyang** [comment]
@peakwinter  I think it was I who did it. The GET request upon client selection was not used, and the meal defaults were loaded during the form refresh. 

I have fixed it in PR #719. I'm closing it now...
