### ISSUE TITLE
Route size monitoring - Dashboard request

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/sous-chef#713]
### Expected Behaviour

When asked whether or not we can accept a new client on any given route, we need to know:

1# the nb. of episodic meals that could be ordered (if all of them ordered on the same day)
 per route.  (adding up meal defaults numbers from all active, paused and pending episodic clients and choosing the biggest number of meals if a client receives different meal quantity on different days)  

2# the nb. of ongoing meals scheduled per route per day. (adding up meal defaults numbers from all active, paused and pending ongoing clients)  

This would take the form of a table. 

````
                       Episodic   *   Mon   Tue   Wed   *   Fri   Sat
CDN       
Centre-Sud
Centre-Ville
Mile-End
McGIll
NDG
Westmount
````

### Actual Behaviour

nothing

### Steps to reproduce

* step 1
* step 2
* ...

**Comment by lingxiaoyang** [comment]
@JeanFrancoisFournier  Here is a proposed route table. The numbers are calculated with the **number** of main dishes, regardless of its size (regular or large). For example, on route Mile-End, on Monday, there are 4 ongoing clients that are ordering 2, 2, 1, 1 main dishes, respectively. Is this correct behaviour?

I added a tooltip (the question mark) in the table head. Do you have other suggestions for this text?

![capture du 2017-03-28 11-17-01](https://cloud.githubusercontent.com/assets/8630726/24413122/809424ea-13a8-11e7-8f9a-bd83b1e0b305.png)
![capture du 2017-03-28 11-17-14](https://cloud.githubusercontent.com/assets/8630726/24413126/83143dfe-13a8-11e7-9e24-3f228aeebc0a.png)

**Comment by lingxiaoyang** [comment]
@JeanFrancoisFournier  Here is a proposed route table. The numbers are calculated with the **number** of main dishes, regardless of its size (regular or large). For example, on route Mile-End, on Monday, there are 4 ongoing clients that are ordering 2, 2, 1, 1 main dishes, respectively, which add up to 6 as displayed in the table. Is this the correct behaviour?

I added a tooltip (the question mark) in the table head. Do you have other suggestions for this text?

![capture du 2017-03-28 11-17-01](https://cloud.githubusercontent.com/assets/8630726/24413122/809424ea-13a8-11e7-8f9a-bd83b1e0b305.png)
![capture du 2017-03-28 11-17-14](https://cloud.githubusercontent.com/assets/8630726/24413126/83143dfe-13a8-11e7-9e24-3f228aeebc0a.png)

**Comment by lingxiaoyang** [comment]
Development note: depends on #719 as it has to inquire meals_default and meals_schedule.

**Comment by lingxiaoyang** [comment]
Development note: depends on #725 as there's been considerable changes on route.

**Comment by lamontfr** [comment]
@lingxiaoyang I will show your proposed solution to Jean-François tomorrow and give you feedback.

**Comment by lamontfr** [comment]
@lingxiaoyang @JeanFrancoisFournier  I discussed this with JF last Friday. Since issue #700 has been solved, we now have daily default meal data for episodic clients. So the revised layout for the route size monitoring should be : 

````
                        *     Mon      Tue     Wed      *    Fri     Sat
CDN                        24 (+ 5)  
Centre-Sud
Centre-Ville
Mile-End
McGIll
NDG
Westmount
````
where for each day, the first number is for ongoing clients and the number in parentheses is for episodic clients,

**Comment by lingxiaoyang** [comment]
@lamontfr  Got it. I assume the numbers "24" and "5" are only the main dishes, regardless of the size (regular/large). Is it correct?

**Comment by lingxiaoyang** [comment]
@lamontfr A quick preview:

![image](https://cloud.githubusercontent.com/assets/8630726/25356764/72a22cda-2909-11e7-9200-84c107449557.png)

**Comment by lamontfr** [comment]
@lingxiaoyang You are correct to count only the main dishes, irrespective of their size. The new layout is exactly what JF explained. Good job !
