### ISSUE TITLE
Can't gulp on Windows when not using Docker

### ISSUE THREAD

**Issue by Jamie22** [savoirfairelinux/sous-chef#728]
### Expected Behaviour

It should generate the static files such as main.min.css and sous-chef.min.js

### Actual Behaviour

Running gulp gives the following error:

> fs.js:952
>   return binding.readdir(pathModule._makeLong(path), options.encoding);
>                  ^
> 
> Error: ENOENT: no such file or directory, scandir 'C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\vendor'
>     at Error (native)
>     at Object.fs.readdirSync (fs.js:952:18)
>     at Object.getInstalledBinaries (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\extensions.js:123:13)
>     at foundBinariesList (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\errors.js:20:15)
>     at foundBinaries (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\errors.js:15:5)
>     at Object.module.exports.missingBinary (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\errors.js:45:5)
>     at module.exports (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\binding.js:15:30)
>     at Object.<anonymous> (C:\Users\jamie\sous-chef\tools\gulp\node_modules\node-sass\lib\index.js:14:35)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)

The node-sass directory is there but there's no vendor directory inside it.

**Comment by lingxiaoyang** [comment]
I didn't replicate this issue on a Windows 10 VM (hosted on Ubuntu 16.04 via VMWare Workstation):

The command `gulp` doesn't exist globally after `npm install --unsafe-perms`, but can be called via `node`:
![image](https://cloud.githubusercontent.com/assets/8630726/25542865/4ce8d2c0-2c22-11e7-94e5-ab818f21c755.png)

I checked the node-sass directory but I found the Windows binding:
![image](https://cloud.githubusercontent.com/assets/8630726/25542888/639cde94-2c22-11e7-9d17-a83d148d2f51.png)

**Comment by lingxiaoyang** [comment]
@Jamie22  Could you try with the updated docs dc2a68c?

**Comment by lingxiaoyang** [comment]
@Jamie22  You should be able to see the downloading process of the sass binding in the logs:

![image](https://cloud.githubusercontent.com/assets/8630726/25621914/d3b492c0-2f20-11e7-9d5e-c76a6d507180.png)

**Comment by erozqba** [comment]
@Jamie22 do you still have this issue?

**Comment by Jamie22** [comment]
Not anymore but I'm able to use Docker now.

**Comment by lingxiaoyang** [comment]
@Jamie22  Thank you!
