### ISSUE TITLE
Orders should not be automatically generated when it is out of an ongoing client's delivery schedule

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#734]
### Expected Behaviour

@lamontfr Please confirm if this is an anomaly of sous-chef.

There are orders automatically generated on every midnight for all ongoing clients. The same logic is executed when the admin clicks on "Generate orders" in kitchen count review step 1. For every ongoing client, if he/she has delivery on that day, there should be an order for what he/she wants.

### Actual Behaviour

An ongoing client may select the days that he/she wants delivery as the delivery schedule, for example, Mon, Wed and Fri. Currently, sous-chef creates the order regardless of delivery schedule. For this example client, sous-chef will create orders on every day, while it should only create when it's Mon, Wed or Fri.

### Steps to reproduce

* step 1: create a test client or modify an existing client, set "delivery type" as Ongoing, select some days other than today in "schedule". Then verify if you have correct information:
![image](https://cloud.githubusercontent.com/assets/8630726/25711279/8ed2c396-30bc-11e7-8712-a832fb591e51.png)

* step 2: make sure that there's no order in "Kitchen Count". Delete them if they already exist.
* step 3: click "Generate orders" and you'll see this test client's order. It should not appear because the client doesn't have delivery today.

### Code reference

1. When clicking "Generate orders":
https://github.com/savoirfairelinux/sous-chef/blob/395ac8252a1de669d46b518f459ba1093a9d47cb/src/delivery/views.py#L1282
https://github.com/savoirfairelinux/sous-chef/blob/395ac8252a1de669d46b518f459ba1093a9d47cb/src/order/models.py#L171-L176 -- no checking for delivery schedule. In fact, it should consult `client.meals_schedule` instead of `client.meals_default`. 

2. Automatic generation at midnight:
https://github.com/savoirfairelinux/sous-chef/blob/395ac8252a1de669d46b518f459ba1093a9d47cb/src/order/management/commands/generateorders.py#L39  -- then goes to the same code.

**Comment by lamontfr** [comment]
@lingxiaoyang I confirm that the expected behavior is correct. However, using current dev 395ac82, I cannot yet reproduce the problem. I will test further.

**Comment by lamontfr** [comment]
@lingxiaoyang I confirm that the bug is present in current dev 395ac82.

**Comment by lingxiaoyang** [comment]
@lamontfr Thank you for confirming! We'll need a unit test for this issue.

**Comment by lamontfr** [comment]
@lingxiaoyang Like you said, the fix is in https://github.com/savoirfairelinux/sous-chef/blob/395ac8252a1de669d46b518f459ba1093a9d47cb/src/order/models.py#L171-L176 but meals_default has variable length so we must look for the tuple having the weekday name rather that directly indexing with the day integer (0-6).
