### ISSUE TITLE
Can't run docker-compose up. GDAL library cannot be found and throws an exception

### ISSUE THREAD

**Issue by andre-lima** [savoirfairelinux/sous-chef#737]
### Expected Behaviour
Server should be up.

### Actual Behaviour
When running `sudo docker-compose up` an exception is thrown. Please see attached log file.
[error_log.txt](https://github.com/savoirfairelinux/sous-chef/files/986710/error_log.txt)

### Steps to reproduce
* clone repo and install docker
* run `sudo docker-compose build`
* run `sudo docker-compose up`
* Observe the issue in the terminal

**Comment by lingxiaoyang** [comment]
The error is caused by a change in Django 1.11:

> In older versions, GDAL is required only for SQLite. Now it’s required for all databases.

https://docs.djangoproject.com/en/1.11/ref/contrib/gis/install/geolibs/

It's better to install this.

**Comment by Jamie22** [comment]
I'm seeing the same error when I run docker-compose up and when I try to run python3 manage.py migrate. I followed the instructions at lingxiaoyang's link, installing GEOS, PROJ.4, and GDAL inside the web container, but it hasn't changed anything. Where do I put the file libgdal.so? I'm using Docker for Windows now.

**Comment by erozqba** [comment]
@Jamie22 could you stop all containers, then remove containers, networks, images and redo a clean setup? Maybe your issue is that you are still using the old containers that don't have GDAL library installed.

**Comment by lingxiaoyang** [comment]
@Jamie22  Normally we don't need to manage the library file `libgdal.so` by ourselves. If you install GDAL with a package manager (e.g., `apt`, `yum`, ...), everything should be automatically managed, and that's what added in this pull request. You'll need to rebuild the container by `docker-compose build`.

**Comment by Jamie22** [comment]
Ok, got it!
