### ISSUE TITLE
Use a larger symbol on map when multiple clients at one stop

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#742]
### Expected Behaviour
(As requested by and discussed with Jean-François on 2017-05-12)
- On a route map, we should clearly see in the blue "drop" label when there are more than one client at a stop.

### Actual Behaviour
- The label at a stop shows the number with a relatively small asterisk compared to the size of the number. This makes it difficult to distinguish from the stops having only one client.

### Suggestions to solve issue
- Increase the font size for only the asterisk OR
- Instead of one asterisk, put four asterisks to make it stand out OR
- Change the color of the blue "drop" when there are many clients.

**Comment by lingxiaoyang** [comment]
@lamontfr  Leaflet doesn't support styling only the asterisk. How about magnifying the entire text?

![image](https://cloud.githubusercontent.com/assets/8630726/26130696/ed21d602-3a63-11e7-81de-af2139627f28.png)

**Comment by lingxiaoyang** [comment]
I'm not very into changing the color as it may not be friendly for visual-impaired people.

**Comment by lamontfr** [comment]
@lingxiaoyang I like very much your first solution : magnifying the entire text for multi-client stops.
