### ISSUE TITLE
In the kitchen count, show when main dish ingredients have been changed

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#747]
### Expected Behaviour
- As a customer manager, after I have chosen the day's main dish in the kitchen count, I want to see immediately when ingredients have been added or removed compared to the dish recipe.
- The "restore recipe" button should be active whenever the ingredients differ from the recipe.

### Actual Behaviour
- In some cases, it seems that the when the main dish ingredients have been modified on a day in the past, the ingredients that are loaded for today's main dish do not correspond to the recipe.
- This may be a bug, but it has not yet been reproduced in dev.

**Comment by lingxiaoyang** [comment]
@lamontfr  Is it related with the date/time configuration on the production machine?
