### ISSUE TITLE
Dockerfile shouldn't use ADD

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#755]
The Dockerfile right now says

```
ADD requirements.txt /code/
...
ADD . /code/
```

https://docs.docker.com/engine/reference/builder/#add doesn't make it that clear, but https://www.ctl.io/developers/blog/post/dockerfile-add-vs-copy/ suggests that ADD is almost always a mistake and that COPY is correct.

**Comment by lingxiaoyang** [comment]
@erozqba  After reading the doc, I think we can simply replace AND with COPY?

**Comment by erozqba** [comment]
@lingxiaoyang yes.

**Comment by lingxiaoyang** [comment]
Merged in #774.
