### ISSUE TITLE
CI server doesn't test docker

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#758]
The INSTALL.md instructions only explain how to install using Docker. I actually found it was easier to use my knowledge of webapps to figure out how to set it up without Docker, which [as I discovered](https://github.com/savoirfairelinux/sous-chef/issues/756#issuecomment-310600425), is what the Travis-CI server thinks too; it doesn't actually test any of the Docker code, which means changes to Dockerfile or docker-compose.yml are not exercised, and more importantly, external version changes in our dependencies, when run on Docker, are not.

I would prefer if non-Docker was the install method, but if you prefer to stick with Docker then please make sure both `docker-compose up` and `docker-compose -f docker-compose.yml -f docker-compose.prod.yml` are tested.

**Comment by lingxiaoyang** [comment]
@kousu I think a CI test on docker is not so critical. I agree with you that `docker-compose.override.yml` is a bad idea and it's better to make it explicit. But then we may not really need the CI test because the docker-compose file is usually straightforward and self-explaining. It would be sufficient after the PR #762. How do you think?

**Comment by kousu** [comment]
I think that all the Docker steps, whether scripted or in manual instructions, are just as much part of the codebase as Django. Not being able to reliably get docker working means delaying deployments and bringing new people on board. I don't know what's involved in setting it up under Travis but I imagine it being tricky and painful; but if that isn't done, I would want a clean build (e.g. ideally in a fresh VM) to be done manually at least once a month.

**Comment by erozqba** [comment]
@kousu The name convention for share docker-compose configurations files use `docker-compose.override.yml` for the default "dev" environements, check here: https://docs.docker.com/compose/extends/

**Comment by lingxiaoyang** [comment]
@kousu I got it wrong. Thanks @erozqba !

**Comment by erozqba** [comment]
@kousu Could you check the PR #775 and give me other suggestions that you find we should include in the Travis-CI tests?
