### ISSUE TITLE
volume souschef_static is unused

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#763]
docker-compose.yml defines

```
   volumes:
      - souschef_static:/code/src/static
```

but staticfiles are placed under /code/src/sous_chef/static, as far as I can tell. This folder here is unused, and unfound by Django when looking for things under /static.

**Comment by lingxiaoyang** [comment]
I think it is completely safe to remove this volume from Docker file. @erozqba How do you think?

**Comment by erozqba** [comment]
@kousu @lingxiaoyang is not safe to remove this volume and it is being used by the Nginx in the production settings to serve static files directly without the intervention of Gunicorn.
