### ISSUE TITLE
Display Version Number

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#766]
I have a request: can we please add the git revision and/or tag onto the footer or the login page?

**Comment by lingxiaoyang** [comment]
@lamontfr Have we talked about this once, maybe in a face-to-face meeting? If so, can you remind me of the specific reason that we decided not to add the commit id?

Sorry I don't remember it anymore. If we've never discussed about it, I would agree with this proposal and it's not difficult to do.

**Comment by kousu** [comment]
I just noticed too that `SOUSCHEF_VERSION=` seems to be printed in the sidebar, but that's manually set by an environment variable, it's not the revision number.

**Comment by lingxiaoyang** [comment]
@kousu  Yes, exactly. You can see #743.

**Comment by lamontfr** [comment]
@kousu @lingxiaoyang I opened issue #743 for this purpose. Issue #766 is a duplicate.

@kousu Please edit `docker-compose.yml` as per the deployment notes in PR #754. If you want you can set `SOUSCHEF_VERSION=` tag + git revision.

**Comment by kousu** [comment]
I'll take this debate to #743.
