### ISSUE TITLE
Request: inline all frontend libraries

### ISSUE THREAD

**Issue by kousu** [savoirfairelinux/sous-chef#767]
There are a few frontend libraries which are externally hosted. It seems like these could be inlined to `/static/`:

https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.js
https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.10/semantic.min.css
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js

**Comment by lingxiaoyang** [comment]
Needs to change gulp file, I think. Refs 89d6febc1a27ef88781cfe8323e1d1310cfc2bcf.

**Comment by lingxiaoyang** [comment]
Fixed by #779. Closing...
