### ISSUE TITLE
Test Environment beta4 : Broken UI for new orders calendar date selection

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#788]
### Expected Behaviour
- The new orders calendar date selection should look like : 

![screenshot at 2017-07-31 08-43-28](https://user-images.githubusercontent.com/8512608/28778433-32c9bf9a-75cd-11e7-850b-fbb7257ed8ed.png)

### Actual Behaviour
- Using the Test environment (Staging beta4), the new orders calendar date selection looks like : 

![screenshot at 2017-07-31 08-42-10](https://user-images.githubusercontent.com/8512608/28778389-fe9efdb6-75cc-11e7-98bc-d35328aaa1b7.png)

**Comment by erozqba** [comment]
@lamontfr I will look into it right now!

**Comment by lamontfr** [comment]
@erozqba Thanks !

**Comment by erozqba** [comment]
@lamontfr The problem here is that for this page, we are used the css styles directly from http://code.jquery.com and the browser block the request because is not over https. I will change this to only use compiled CSS and JavaScript.
