### ISSUE TITLE
A created order should have at least one order item

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#803]
### Expected Behaviour
- When a user creates a new order, if he does not enter any quantity and does not select one of "delivery", "pickup" or "visit", he should get an error message.

### Actual Behaviour
- When a user creates a new order, if he does not enter any quantity and does not select one of "delivery", "pickup" or "visit", the order is created with no order items associated to it.

### Steps to reproduce
- Orders / New order / choose client X / choose date / enter main dish size / Place orders / see message "order created"
- Orders / choose client X / Search / click on view (eye icon) next to last order / in order details, notice that we have no order items

**Comment by JeanFrancoisFournier** [comment]
right!
