### ISSUE TITLE
Main dish price is higher for large size ?

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#805]
### Expected Behaviour
- For clients paying the default price, the main dish in an order should be priced $ 5.50 each for regular size and 6.50 for large size.
- For clients paying the low-income price, the main dish in an order should be priced $ 4.50 each for regular size and 5.25 for large size.

### Actual Behaviour
- For some clients, in manually created or generated orders, the main dish price shows as $ 6.50 but the dish size is not shown which makes the price doubtful.

### Steps to reproduce
- (In SousChef Test Environment) : Orders / New order / choose client X / choose a date / choose Large size / set quantities to 1 / Place orders / Clients / Choose client X / Orders / view last order detail / See main dish is $ 6.50.

**Comment by JeanFrancoisFournier** [comment]
Pricing at the Roulant
---------------------------

Default pricing: 
   Regular meals 5.50$ (with one side dish included)
   Large meals 6.50$ (with one side dish included)
   Extra side dishes 1.00$ each

Low-Income
   Regular meals 4.50$ (with one side dish included)
   Large meals 5.25$ (with one side dish included)
   Extra side dishes 0.75$

**Comment by lamontfr** [comment]
@JeanFrancoisFournier Since the actual behavior is correct, I am closing this issue.
