### ISSUE TITLE
In kitchen count report, clashing ingredients are repeated

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#811]
### Expected Behaviour
- The "clashing ingredients" column on the kitchen count report should, in a given row, have a single ingredient or a combination of different ingredients.

### Actual Behaviour
- The "clashing ingredients" column on the kitchen count report sometimes shows in a given row the same ingredient repeated.

### Steps to reproduce
- In SousChef Test environment : Kitchen count / generate orders / step 2 / choose "Ginger pork" as main dish / choose a side ingredient / confirm ingredients / step 3 / see "ground pork" repeated in row 2.

**Comment by JeanFrancoisFournier** [comment]
Right!
that's probably just a duplicate entry in theingredients/reciped/categories from the admin... but if it's not, of course it would need to be looked at

**Comment by lamontfr** [comment]
@JeanFrancoisFournier You are right, In the database the restricted_item "pork", the ingredient "Ground pork" was entered twice. Deleting the extra one fixed the problem.
