### ISSUE TITLE
Wrong dates on labels

### ISSUE THREAD

**Issue by JeanFrancoisFournier** [savoirfairelinux/sous-chef#820]
### Expected Behaviour

When generating labels in the Kitchen count process, the date displayed and printed should be accurate.

### Actual Behaviour

The date displayed and printed is not accurate.

### Steps to reproduce

- access the Kitchen count from the left side tabs
- click on Step 2 "Ingredients"
- Select a recipe to load the ingredients and pick a random side dish ingredient
- Click confirm all ingredients
- Click "Next: Print kitchen count"
- Click on the pink "Labels" button
- Open the PDF and look at the date

**Comment by JeanFrancoisFournier** [comment]
Also, it seems now that the date is stuck on December 1st.
Some clients thought we we're sending them old meals.

**Comment by lamontfr** [comment]
@JeanFrancoisFournier I found the cause and fixed it. Sorry it took so long. After Ernesto or Ling has tested, I will merge this fix, make a new release and ask @kousu to install it in souschef test.
